Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2024-10, with the labels that each got.

#5 API Proposal
  docs/proposals/002-api-proposal/glossary.md
  docs/proposals/002-api-proposal/images/gw_w_lsp.svg
  docs/proposals/002-api-proposal/images/lsp.svg
  docs/proposals/002-api-proposal/proposal.md
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#14 Add initial ext proc implementation with LoRA affinity
  pkg/ext-proc/Dockerfile
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/metrics.go
  pkg/ext-proc/backend/pod_client.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/benchmark/benchmark.go
  pkg/ext-proc/go.mod
  pkg/ext-proc/go.sum
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/scheduling/types.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, tide/merge-method-squash

#17 Improve the filter to return multiple preferred pods instead of one; also fix metrics update bug
  pkg/ext-proc/backend/metrics.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#26 Refactor: Define PodMetricsClient interface and hide implementation details of vllm metrics processing
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/pod_client.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/benchmark/benchmark.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#25 Add priority based scheduling
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/go.mod
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/scheduling/types.go
Labels: cncf-cla: yes, approved, lgtm, tide/merge-method-squash, size/XL

#28 Update vllm deployment example to use 1 GPU as tensor parallelism is 1
  examples/poc/manifests/vllm/vllm-lora-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#29 Add a hermetic e2e test with fake backend pods
  pkg/ext-proc/benchmark/benchmark.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/hermetic_test.go
  pkg/ext-proc/test/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#33 Fix mutierr appending; add a unit test.
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/vllm/metrics.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#35 Some minor fixes in Envoy setup
  pkg/README.md
  pkg/manifests/ext_proc.yaml
  pkg/manifests/gateway.yaml
  pkg/manifests/patch_policy.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S
