Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2024-09, with the labels that each got.

#6 Update OWNERS
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4 PoC implementation
  examples/poc/README.md
  examples/poc/envoy-gateway-bootstrap.png
  examples/poc/ext-proc/Dockerfile
  examples/poc/ext-proc/cache/cache.go
  examples/poc/ext-proc/go.mod
  examples/poc/ext-proc/go.sum
  examples/poc/ext-proc/handlers/handlers.go
  examples/poc/ext-proc/main.go
  examples/poc/ext-proc/metrics/metrics.go
  examples/poc/ext-proc/scheduling/fairness.go
  examples/poc/manifests/ext-proc.yaml
  examples/poc/manifests/gateway.yaml
  examples/poc/manifests/vllm/vllm-lora-deployment.yaml
  examples/poc/manifests/vllm/vllm-lora-service.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#7 Fix build for ext-proc example
  examples/poc/ext-proc/cache/cache.go
  examples/poc/ext-proc/main.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#8 Simplify POC installation
  examples/poc/README.md
  examples/poc/manifests/ext-proc.yaml
  examples/poc/manifests/installation.yaml
  examples/poc/manifests/samples/gateway.yaml
  examples/poc/manifests/samples/vllm-lora-deployment.yaml
  examples/poc/manifests/samples/vllm-lora-service.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#9 docs: markdown perfs
  examples/poc/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#11 fix: inconsistent secret key with deployment
  examples/poc/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#13 Updating top level README
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/M
