Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2024-11, with the labels that each got.

#37 Update targetModel in request body
  pkg/ext-proc/handlers/request.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#39 Adding circuit breaker and timeout layers to avoid Gateway 5xx errors.
  pkg/README.md
  pkg/manifests/ext_proc.yaml
  pkg/manifests/gateway.yaml
  pkg/manifests/patch_policy.yaml
  pkg/manifests/traffic_policy.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#15 Simulation code for llm inference gateway
  simulations/llm_ig_simulation/src/__init__.py
  simulations/llm_ig_simulation/src/benchmark_one_server.py
  simulations/llm_ig_simulation/src/constants.py
  simulations/llm_ig_simulation/src/continous_batching.py
  simulations/llm_ig_simulation/src/llmactor.py
  simulations/llm_ig_simulation/src/loadbalancer.py
  simulations/llm_ig_simulation/src/main.py
  simulations/llm_ig_simulation/src/request.py
  simulations/llm_inference_gateway_simulation.ipynb
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#42 Add myself to approvers
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#31 Dynamic lora load/unload sidecar
  tools/dynamic-lora-sidecar/.gitignore
  tools/dynamic-lora-sidecar/Dockerfile
  tools/dynamic-lora-sidecar/README.md
  tools/dynamic-lora-sidecar/deployment.yaml
  tools/dynamic-lora-sidecar/requirements.txt
  tools/dynamic-lora-sidecar/screenshots/configmap-change.png
  tools/dynamic-lora-sidecar/screenshots/lora-syncer-sidecar.png
  tools/dynamic-lora-sidecar/screenshots/vllm-logs.png
  tools/dynamic-lora-sidecar/sidecar/sidecar.py
  tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
  tools/dynamic-lora-sidecar/sidecar/validation.yaml
Labels: cncf-cla: yes, approved, lgtm, tide/merge-method-squash, size/XL

#36 LLMServerPool Implementation
  .gitignore
  Dockerfile
  examples/poc/ext-proc/go.mod
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/llmlserverpool_reconciler_test.go
  pkg/ext-proc/backend/llmserverpool_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/go.mod
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, approved, lgtm, tide/merge-method-squash, size/XL

#47 Updating API and generating code
  api/v1alpha1/llmserverpool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1alpha1/llmserverpoolspec.go
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/llmlserverpool_reconciler_test.go
  pkg/ext-proc/backend/llmserverpool_reconciler.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#51 Do not fail Init if fetch metrics fails. It can recover gracefully.
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#48 llmservice reconciler implementation
  api/v1alpha1/llmserverpool_types.go
  client-go/applyconfiguration/api/v1alpha1/llmserverpoolspec.go
  config/crd/bases/gateway.inference.networking.x-k8s.io_llmserverpools.yaml
  examples/poc/README.md
  examples/poc/envoy-gateway-bootstrap.png
  examples/poc/manifests/llmservice.yaml
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/llmservice_reconciler.go
  pkg/ext-proc/backend/llmservice_reconciler_test.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#52 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#53 Fixing hermetic_test, small formatting changes
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/test/hermetic_test.go
  pkg/ext-proc/test/utils.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#40 Add myself to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm
