Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2024-12, with the labels that each got.

#57 Add dependency updates
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, lgtm, size/S

#63 integrating LLMService & random weighted draw
  api/v1alpha1/groupversion_info.go
  config/crd/bases/gateway.inference.k8s.io_llmserverpools.yaml
  config/crd/bases/gateway.inference.networking.x-k8s.io_llmservices.yaml
  config/crd/bases/inference.networking.x-k8s.io_llmserverpools.yaml
  config/crd/bases/inference.networking.x-k8s.io_llmservices.yaml
  config/crd/kustomization.yaml
  config/rbac/llmserverpool_editor_role.yaml
  config/rbac/llmserverpool_viewer_role.yaml
  config/rbac/llmservice_editor_role.yaml
  config/rbac/llmservice_viewer_role.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#64 Integrating LLMService with weight splitting
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#65 Fix build and test
  go.mod
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/hermetic_test.go
  pkg/ext-proc/test/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#67 Makefile fixes with generated output
  Makefile
  client-go/applyconfiguration/api/v1alpha1/llmserverpool.go
  client-go/applyconfiguration/api/v1alpha1/llmservice.go
  client-go/applyconfiguration/internal/internal.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_llmserverpool.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_llmservice.go
  client-go/clientset/versioned/typed/api/v1alpha1/llmserverpool.go
  client-go/clientset/versioned/typed/api/v1alpha1/llmservice.go
  client-go/informers/externalversions/api/v1alpha1/llmserverpool.go
  client-go/informers/externalversions/api/v1alpha1/llmservice.go
  client-go/informers/externalversions/generic.go
  client-go/listers/api/v1alpha1/llmserverpool.go
  client-go/listers/api/v1alpha1/llmservice.go
  hack/update-codegen.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#81 Manifest updates
  examples/poc/manifests/llmservice.yaml
  examples/poc/manifests/vllm/vllm-lora-deployment.yaml
  examples/poc/manifests/vllm/vllm-lora-service.yaml
  pkg/manifests/ext_proc.yaml
  pkg/manifests/gateway.yaml
  pkg/manifests/patch_policy.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#78 Enhancements to LLM Instance Gateway: Scheduling Logic, and Documentation Updates
  docs/schedular-flowchart.png
  examples/poc/manifests/vllm/vllm-lora-deployment.yaml
  pkg/README.md
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, tide/merge-method-squash, size/M

#79 Bug fixes: 1. NPE when model is not found 2. Port is considered 0 when LLMServerPool is not initialized
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/llmlserverpool_reconciler_test.go
  pkg/ext-proc/backend/llmserverpool_reconciler.go
  pkg/ext-proc/backend/llmservice_reconciler.go
  pkg/ext-proc/backend/llmservice_reconciler_test.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/main.go
  pkg/ext-proc/test/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#94 Adding simple cloudbuild file that builds, tags, and pushes the docker image
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#54 switch to using upstream vllm with new metric
  examples/poc/manifests/vllm/vllm-lora-deployment.yaml
  go.mod
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#92 Change from SIG Apps to SIG Network
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#90 Add response body handler
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/response_test.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#114 API compliance fix and build fixes
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  config/crd/bases/inference.networking.x-k8s.io_llmserverpools.yaml
  config/crd/bases/inference.networking.x-k8s.io_llmservices.yaml
  config/crd/kustomization.yaml
  config/rbac/inferencemodel_editor_role.yaml
  config/rbac/inferencemodel_viewer_role.yaml
  config/rbac/inferencepool_editor_role.yaml
  config/rbac/inferencepool_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/samples/gateway_v1alpha1_inferencemodel.yaml
  config/samples/gateway_v1alpha1_inferencepool.yaml
  config/samples/kustomization.yaml
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#123 update the linter version
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#121 Disable response body processing
  examples/poc/manifests/gateway/enable_patch_policy.yaml
  examples/poc/manifests/gateway/ext_proc.yaml
  examples/poc/manifests/gateway/gateway.yaml
  examples/poc/manifests/gateway/patch_policy.yaml
  pkg/ext-proc/handlers/response.go
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#118 Adding initial docs infra
  .gitignore
  Makefile
  hack/mkdocs/image/Dockerfile
  hack/mkdocs/image/entrypoint.sh
  hack/mkdocs/image/requirements.txt
  mkdocs.yml
  netlify.toml
  site-src/.mkdocs-exclude
  site-src/api-types/inferencemodel.md
  site-src/api-types/inferencepool.md
  site-src/concepts/api-overview.md
  site-src/concepts/glossary.md
  site-src/concepts/roles-and-personas.md
  site-src/concepts/use-cases.md
  site-src/contributing/devguide.md
  site-src/contributing/index.md
  site-src/faq.md
  site-src/gieps/giep-116/index.md
  site-src/gieps/giep-116/metadata.yaml
  site-src/gieps/overview.md
  site-src/guides/implementers.md
  site-src/guides/index.md
  site-src/images/logo/logo-text-large-horizontal-white.png
  site-src/implementations.md
  site-src/index.md
  site-src/overrides/partials/header.html
  site-src/reference/spec.md
  site-src/stylesheets/extra.css
Labels: cncf-cla: yes, approved, lgtm, size/XL

#125 Lint fixes/updating .golangci to not use deprecated linter
  .golangci.yml
  Makefile
  api/v1alpha1/inferencepool_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  pkg/ext-proc/main.go
  pkg/ext-proc/test/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#126 fixing some lint errors
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#127 Fix the make build command and add main tag to the latest image
  Makefile
  cloudbuild.yaml
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#128 Fixing the build command
  Dockerfile
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/S

#134 Fixed the rest of the lint errors and updating the linters
  .golangci.yml
  Makefile
  api/v1alpha1/inferencemodel_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/hermetic_test.go
  pkg/ext-proc/test/utils.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#136 Remove outdated configurations and ensure the tutorial runs smoothly
  examples/poc/manifests/inferencepool-with-model.yaml
  pkg/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S
