Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-02, with the labels that each got.

#266 Proposals cleanup
  docs/example.md
  docs/proposals/002-api-proposal/README.md
  docs/proposals/003-endpoint-picker-protocol/README.md
  examples/placeholder.md
  mkdocs.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#162 InferencePool config proposal for API review
  Makefile
  api/v1alpha1/inferencepool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1alpha1/endpointpickerconfig.go
  client-go/applyconfiguration/api/v1alpha1/extension.go
  client-go/applyconfiguration/api/v1alpha1/extensionconnection.go
  client-go/applyconfiguration/api/v1alpha1/extensionreference.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolspec.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  pkg/manifests/ext_proc.yaml
  test/integration/hermetic_test.go
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL

#275 Add TRACE log level for the metric refresh loop
  docs/dev.md
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/util/logging/logging_const.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#273 Using constants for the repeated values
  pkg/ext-proc/test/benchmark/benchmark.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#270 Update default target-pod and inject it into response metadata
  docs/proposals/003-endpoint-picker-protocol/README.md
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
  pkg/ext-proc/server/runserver.go
  pkg/manifests/gateway/patch_policy.yaml
  pkg/manifests/vllm/deployment.yaml
  test/integration/hermetic_test.go
  test/testdata/envoy.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#237 [Metrics] Add grafana dashboard for Inference extension and vLLM metrics
  tools/dashboards/README.md
  tools/dashboards/inference_gateway.json
  tools/dashboards/inference_gateway_dashboard_1.png
  tools/dashboards/inference_gateway_dashboard_2.png
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#274 Release setup
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new-release.md
  .gitignore
  Makefile
Labels: cncf-cla: yes, size/L, approved, lgtm

#279 Updating to the new gcr repo
  .github/ISSUE_TEMPLATE/new-release.md
  Makefile
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#271 Replace EndpointSlice reconciler with pod list backed by informer
  .golangci.yml
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/testing/lister.go
  pkg/ext-proc/util/testing/wrappers.go
  pkg/manifests/ext_proc.yaml
  pkg/manifests/vllm/deployment.yaml
  test/e2e/e2e_suite_test.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#285 Updates artifacts for v0.1.0-rc1 release
  pkg/README.md
  pkg/manifests/ext_proc.yaml
  pkg/manifests/vllm/deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#291 feat: adds initial release automation
  .github/ISSUE_TEMPLATE/new-release.md
  Makefile
  hack/release-quickstart.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#301 Revert "Replace EndpointSlice reconciler with pod list backed by informers"
  .golangci.yml
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/testing/lister.go
  pkg/ext-proc/util/testing/wrappers.go
  pkg/manifests/ext_proc.yaml
  pkg/manifests/vllm/deployment.yaml
  test/e2e/e2e_suite_test.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#302 Fixing small linter complaints
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/inferencepool_types.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#278 In hermetic test, add additional test cases and move k8sClient object creation so it's called once for all tests
  test/integration/hermetic_test.go
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#304 [Metrics] Add average kv cache and waiting queue size metrics for inference pool
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/main.go
  pkg/ext-proc/metrics/README.md
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/metrics/testdata/kv_cache_avg_metrics
  pkg/ext-proc/metrics/testdata/queue_avg_size_metrics
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#308 Move getting started guide to docs site
  pkg/README.md
  site-src/guides/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#309 site-source: Fix 'Bakcground' misspell in API concepts page
  site-src/concepts/api-overview.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#314 Mkdocs fixes
  site-src/concepts/api-overview.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#317 Remove gci linter
  .golangci.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#286 fix: adds ErrorNotFound Handling for InferenceModel Reconciler
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#311 site-src: Replace k8sgateway with kgateway & fix spelling in roles-and-personas.md
  site-src/concepts/roles-and-personas.md
  site-src/implementations.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#318 Fix: Go Mod Imports
  api/doc.go
  api/v1alpha1/doc.go
  client-go/applyconfiguration/api/v1alpha1/extension.go
  client-go/applyconfiguration/api/v1alpha1/extensionconnection.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodel.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodelspec.go
  client-go/applyconfiguration/api/v1alpha1/inferencepool.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolspec.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencepool.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/interface.go
  client-go/informers/externalversions/api/v1alpha1/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/v1alpha1/interface.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/listers/api/v1alpha1/inferencemodel.go
  client-go/listers/api/v1alpha1/inferencepool.go
  go.mod
  hack/update-codegen.sh
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler_test.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/integration/hermetic_test.go
  test/utils/utils.go
  test/utils/wrappers.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#322 Updates EPP Deployment and Release Doc/Script
  .github/ISSUE_TEMPLATE/new-release.md
  hack/release-quickstart.sh
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#319 Delete InferenceModels from the datastore when deletionTimestamp is set
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#267 Actually init logging using Zap
  go.mod
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, approved, lgtm, size/M, needs-ok-to-test

#265 Remove fatal log calls in executable code
  pkg/ext-proc/internal/runnable/grpc.go
  pkg/ext-proc/internal/runnable/leader_election.go
  pkg/ext-proc/main.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/server/runserver_test.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#294 feat: Adds e2e test script
  hack/test-e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#300 Replacing endpointSlice Reconciler with a direct Pod Reconciler
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/pod_reconciler.go
  pkg/ext-proc/backend/pod_reconciler_test.go
  pkg/ext-proc/main.go
  pkg/ext-proc/server/runserver.go
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL

#288 feat: adds image-load and kind-load Make targets
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/S

#330 Use structured logging
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/logging/fatal.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#335 Add TLS support with self-signed certificate.
  pkg/ext-proc/main.go
  pkg/ext-proc/server/runserver.go
  pkg/manifests/gateway/patch_policy.yaml
  test/integration/hermetic_test.go
  test/testdata/envoy.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#339 Fix cloudbuild rule for the LoRA syncer image
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#337 Use contextual logging
  docs/dev.md
  go.mod
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler_test.go
  pkg/ext-proc/backend/pod_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/response_test.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/server/runserver_test.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/logging/fatal.go
  pkg/ext-proc/util/logging/logger.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#338 Fixes to the adapter rollouts guide
  mkdocs.yml
  pkg/manifests/inferencemodel.yaml
  pkg/manifests/vllm/deployment-with-syncer.yaml
  pkg/manifests/vllm/deployment.yaml
  site-src/guides/adapter-rollout.md
  site-src/guides/dynamic-lora.md
  site-src/guides/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#350 Consolidating all storage behind datastore
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler_test.go
  pkg/ext-proc/backend/pod_reconciler.go
  pkg/ext-proc/backend/pod_reconciler_test.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/types.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/server/runserver_test.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/testing/wrappers.go
  pkg/manifests/vllm/deployment.yaml
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#364 fixed a typo - close a bash markdown
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#363 Added controller and datastore package
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/controller/inferencemodel_reconciler.go
  pkg/ext-proc/controller/inferencemodel_reconciler_test.go
  pkg/ext-proc/controller/inferencepool_reconciler.go
  pkg/ext-proc/controller/inferencepool_reconciler_test.go
  pkg/ext-proc/controller/pod_reconciler.go
  pkg/ext-proc/controller/pod_reconciler_test.go
  pkg/ext-proc/datastore/datastore.go
  pkg/ext-proc/datastore/datastore_test.go
  pkg/ext-proc/datastore/types.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#368 Move pkg/ext-proc -> cmd/ext-proc
  Dockerfile
  cmd/ext-proc/health.go
  cmd/ext-proc/main.go
  go.mod
  internal/runnable/grpc.go
  internal/runnable/leader_election.go
  pkg/ext-proc/server/runserver.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#370 added license header to all .go files
  cmd/ext-proc/health.go
  cmd/ext-proc/main.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/provider_test.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/controller/inferencemodel_reconciler.go
  pkg/ext-proc/controller/inferencemodel_reconciler_test.go
  pkg/ext-proc/controller/inferencepool_reconciler.go
  pkg/ext-proc/controller/inferencepool_reconciler_test.go
  pkg/ext-proc/controller/pod_reconciler.go
  pkg/ext-proc/controller/pod_reconciler_test.go
  pkg/ext-proc/datastore/datastore.go
  pkg/ext-proc/datastore/datastore_test.go
  pkg/ext-proc/datastore/types.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/response_test.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/scheduling/types.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/server/runserver_test.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/utils.go
  pkg/ext-proc/util/logging/fatal.go
  pkg/ext-proc/util/logging/logger.go
  pkg/ext-proc/util/logging/logging_const.go
  pkg/ext-proc/util/testing/wrappers.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, needs-ok-to-test

#366 fix inference extension not correctly scrape pod metrics
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/controller/pod_reconciler_test.go
  pkg/ext-proc/datastore/datastore.go
  pkg/ext-proc/datastore/types.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#371 Move pkg/manifests -> config/manifests
  config/manifests/ext_proc.yaml
  config/manifests/gateway/enable_patch_policy.yaml
  config/manifests/gateway/extension_policy.yaml
  config/manifests/gateway/gateway.yaml
  config/manifests/gateway/patch_policy.yaml
  config/manifests/gateway/traffic_policy.yaml
  config/manifests/inferencemodel.yaml
  config/manifests/vllm/deployment.yaml
  hack/release-quickstart.sh
  site-src/guides/index.md
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#269 [Metrics] Add request error metrics
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/metrics/README.md
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/metrics/testdata/request_error_total_metric
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/util/error/error.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#373 Move pkg/ext-proc/metrics/README.md -> site-src/guides/metrics.md
  mkdocs.yml
  site-src/guides/metrics.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#377 Defining an outer metadata struct as part of the extproc endpoint picking protocol
  cmd/epp/main.go
  docs/proposals/003-endpoint-picker-protocol/README.md
  pkg/epp/handlers/request.go
  pkg/epp/handlers/server.go
  pkg/epp/server/runserver.go
  pkg/epp/test/utils.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#374 Draft a revised README.md
  README.md
  docs/inference-gateway-architecture.svg
Labels: cncf-cla: yes, approved, lgtm, size/S

#386 Add README.md file to the epp pkg
  docs/scheduler-flowchart.png
  pkg/epp/README.md
  pkg/scheduling.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#387 Split the proxy and model server protocols for easy reference
  README.md
  docs/proposals/003-model-server-protocol/README.md
  docs/proposals/004-endpoint-picker-protocol/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#389 [Metric] Add inference pool and request error metrics to the dashboard
  tools/dashboards/inference_gateway.json
Labels: cncf-cla: yes, approved, lgtm, size/XL

#384 Switch to gcr.io/distroless/static:nonroot base image
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#390 fix context canceled recv error handling
  pkg/epp/handlers/server.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#396 Added endpoint picker diagram
  docs/endpoint-picker.svg
  pkg/epp/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#400 Adding a roadmap to README
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#397 added inferencemodel predicate + minor changes in logging
  cmd/epp/main.go
  pkg/epp/controller/inferencemodel_reconciler.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#410 Syncing getting started guide all to main
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#412 fixed typo in filepath in website guide page
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#393 Fix InferenceModel deletion logic
  cmd/epp/main.go
  pkg/epp/backend/provider_test.go
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/server/runserver.go
  pkg/epp/test/utils.go
  pkg/epp/util/testing/diff.go
  pkg/epp/util/testing/wrappers.go
  test/e2e/e2e_suite_test.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#420 Updated yamls to use v1alpha2
  config/manifests/ext_proc.yaml
  config/manifests/inferencemodel.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#421 removed the EndpointPickerNotHealthy condition form pool status
  api/v1alpha2/inferencepool_types.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#413 [Metrics] Add metrics validation in integration test
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#418 predicate follow up PR to remove the check from Reconcile func
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#428 Mis cleanup
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/handlers/request.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#417 fix metric scrape port not updated when inference pool target port updated
  pkg/epp/backend/fake.go
  pkg/epp/backend/provider.go
  pkg/epp/backend/provider_test.go
  pkg/epp/backend/vllm/metrics.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/types.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#427 make ModelName immutable and fix model weight
  api/v1alpha2/inferencemodel_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M
