Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-09, with the labels that each got.

#1504 feat(helm): add affinity and tolerations to epp-deployment
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1280 typo: add vLLM Prefix Cache & LoRA Adapters links
  site-src/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1522 fix: fixed helm
  config/charts/inferencepool/templates/inferencepool.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1523 Perf updates
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/scheduler_profile.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1528 follow up - improving logging perf issues in few more places
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
Labels: cncf-cla: yes, approved, lgtm, size/S, kind/cleanup

#1534 Fixing test flake
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1533 adding elevran as code reviewer instead of shaneutt
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1537 Bumps k8s.io Deps to v0.34.0
  client-go/applyconfiguration/api/v1/inferencepool.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjective.go
  client-go/applyconfiguration/apix/v1alpha2/inferencepool.go
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/fake/clientset_generated.go
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#1540 Helm fix
  config/charts/inferencepool/values.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1551 fix helm chart support for gke v1alpha2.
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/gke.yaml
  config/charts/inferencepool/templates/rbac.yaml
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S

#1552 Merge shuffle score pods logic
  pkg/epp/scheduling/framework/plugins/picker/common.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test, kind/cleanup

#1554 Added envoy proxy ai-gateway
  config/manifests/gateway/envoyaigateway/gateway.yaml
  config/manifests/gateway/envoyaigateway/httproute.yaml
  hack/verify-manifests.sh
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1560 fix-import-groups
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test, kind/cleanup

#1561 fix flake in weighted random picker
  pkg/epp/scheduling/framework/plugins/picker/picker_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, kind/flake

#1564 Main uniquely name crbac
  config/charts/inferencepool/templates/_helpers.tpl
  config/charts/inferencepool/templates/rbac.yaml
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1518 Update priority in EPP flow control from uint to int
  pkg/epp/flowcontrol/contracts/mocks/mocks.go
  pkg/epp/flowcontrol/contracts/registry.go
  pkg/epp/flowcontrol/controller/internal/filter.go
  pkg/epp/flowcontrol/controller/internal/filter_test.go
  pkg/epp/flowcontrol/controller/internal/processor.go
  pkg/epp/flowcontrol/controller/internal/processor_test.go
  pkg/epp/flowcontrol/framework/mocks/mocks.go
  pkg/epp/flowcontrol/framework/policies.go
  pkg/epp/flowcontrol/registry/config.go
  pkg/epp/flowcontrol/registry/managedqueue_test.go
  pkg/epp/flowcontrol/registry/registry.go
  pkg/epp/flowcontrol/registry/registry_test.go
  pkg/epp/flowcontrol/registry/shard.go
  pkg/epp/flowcontrol/registry/shard_test.go
  pkg/epp/flowcontrol/types/flow.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1565 Revert "uniquely name CRBAC (#1545)"
  config/charts/inferencepool/templates/_helpers.tpl
  config/charts/inferencepool/templates/rbac.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1544 chore: remove unneeded logging before returning error
  internal/runnable/grpc.go
  pkg/bbr/handlers/server.go
  pkg/bbr/server/runserver.go
  pkg/epp/controller/inferenceobjective_reconciler.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/server.go
  pkg/epp/server/runserver.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test, kind/cleanup

#1589 docs: dashboards README metrics link fix
  tools/dashboards/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1581 refactor: flow control config
  pkg/epp/flowcontrol/config.go
  pkg/epp/flowcontrol/config_test.go
  pkg/epp/flowcontrol/controller/config.go
  pkg/epp/flowcontrol/controller/config_test.go
  pkg/epp/flowcontrol/controller/controller.go
  pkg/epp/flowcontrol/controller/controller_test.go
  pkg/epp/flowcontrol/registry/config.go
  pkg/epp/flowcontrol/registry/config_test.go
  pkg/epp/flowcontrol/registry/registry.go
  pkg/epp/flowcontrol/registry/registry_test.go
  pkg/epp/flowcontrol/registry/shard_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test, kind/cleanup

#1498 Add BBR docs, example deployment
  README.md
  config/manifests/bbr-example/httproute_bbr.yaml
  config/manifests/bbr-example/vllm-phi4-mini.yaml
  pkg/bbr/README.md
  site-src/guides/index.md
  site-src/guides/serve-multiple-genai-models.md
  site-src/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test, kind/documentation

#1603 Updates gateway manifests for v1 InferencePool
  config/manifests/gateway/agentgateway/httproute.yaml
  config/manifests/gateway/envoyaigateway/httproute.yaml
  config/manifests/gateway/istio/httproute.yaml
  config/manifests/gateway/kgateway/httproute.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm, kind/documentation

#1605 docs: remove duplication in multimodel serving guide
  site-src/guides/serve-multiple-genai-models.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test, kind/documentation

#1610 helm: add NAMESPACE env var to EPP deployment for pool namespace
  config/charts/inferencepool/templates/epp-deployment.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1612 chore: bump sim version
  config/manifests/vllm/sim-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1613 Rename prefix scorer HashBlockSize to BlockSize
  pkg/epp/config/loader/configloader_test.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  site-src/guides/epp-configuration/config-text.md
  site-src/guides/epp-configuration/prefix-aware.md
  test/testdata/configloader_1_test.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1618 Remove duplicate gcpbackendpolicy and healthcheckpolicy config
  config/manifests/gateway/gke/gcp-backend-policy.yaml
  config/manifests/gateway/gke/healthcheck.yaml
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S

#1620 Consolidate ha config into a single enableLeaderElection, also fix rolling update stuck bug
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/gke.yaml
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M

#1622 feat: Adapt flow control to per-request saturation
  pkg/epp/flowcontrol/contracts/mocks/mocks.go
  pkg/epp/flowcontrol/contracts/saturationdetector.go
  pkg/epp/flowcontrol/controller/controller.go
  pkg/epp/flowcontrol/controller/controller_test.go
  pkg/epp/flowcontrol/controller/internal/filter.go
  pkg/epp/flowcontrol/controller/internal/filter_test.go
  pkg/epp/flowcontrol/controller/internal/processor.go
  pkg/epp/flowcontrol/controller/internal/processor_test.go
  pkg/epp/flowcontrol/types/mocks/mocks.go
  pkg/epp/flowcontrol/types/request.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1623 fix missing GCPBakendPolicy.
  config/charts/inferencepool/templates/gke.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1628 use replicas field in helm to decide if EPP should run in HA mode
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/leader-election-rbac.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S, kind/cleanup

#1633 Explicitly set pool-namespace flag for wider compatibility
  config/charts/inferencepool/templates/epp-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1381 enable istio as a provider + configuring destinationRule
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/istio.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1645 update automatically the helm chart version used in the quickstart guide
  hack/release-quickstart.sh
  site-src/guides/index.md
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1653 Loosen validation for inference pool crd to support up to 8 ports per inference pool
  api/v1/inferencepool_types.go
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  go.mod
  go.sum
  test/cel/inferencepool_test.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1646 support vLLM cache salting in prefix aware scorer
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/types/types.go
  pkg/epp/util/request/body_test.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1374 Proposal for Multi-Cluster InferencePools
  docs/proposals/1374-multi-cluster-inference/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test
