Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-05, with the labels that each got.

#746 Parse request x-request-id and expose it in contextual logger
  pkg/bbr/handlers/server.go
  pkg/epp/handlers/server.go
  pkg/epp/util/request/headers.go
  pkg/epp/util/request/headers_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#771 put SchedulerConfig fields private again. added NewSchedulerConfig func
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#745 Create unit test for request handler
  pkg/epp/handlers/request_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#773 Add feature request link for adding Triton LoRA metric
  site-src/implementations/model-servers.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#775 passing headers to scheduler plugins
  pkg/epp/handlers/request.go
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#780 Update istio version
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#784 docs: fixed inference pool docs
  site-src/concepts/api-overview.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#788 Healthcheck fix
  .gitignore
  cmd/bbr/health.go
  cmd/epp/health.go
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/manifests/inferencepool-resources.yaml
  go.mod
  go.sum
  test/testdata/inferencepool-e2e.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#789 Docs: Updates Benchmark Guide
  config/manifests/benchmark/benchmark.yaml
  site-src/guides/index.md
  site-src/performance/benchmark/index.md
  tools/benchmark/benchmark.ipynb
Labels: cncf-cla: yes, approved, lgtm, size/M

#793 e2e: Fixes 404 Not Found Error
  test/e2e/epp/e2e_suite_test.go
  test/e2e/epp/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#781 EPP architectural refactor
  pkg/epp/handlers/request.go
  pkg/epp/handlers/request_test.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/server_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#796 remove empty request_test.go file.
  pkg/epp/handlers/request_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#802 Clean up filters
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/filter/filter.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#803 Refactor: Improve env utility
  pkg/epp/util/env/env.go
  pkg/epp/util/env/env_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#797 refactor scheduler filters package
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/plugins/filter/filter.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/filter/has_capacity_filter.go
  pkg/epp/scheduling/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/plugins/filter/sheddable_request_filter.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#804 fix labels not cloned bug
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/pod.go
  pkg/epp/scheduling/scheduler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#810 fixed datastore bug to clean all go routines when pool is unset
  pkg/epp/datastore/datastore.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#811 Optimize Dockerfile for Multiple Extensions
  Dockerfile
  bbr.Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#809 merge has capacity filter with sheddable filter.
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/filter/sheddable_capacity_filter.go
  pkg/epp/scheduling/plugins/filter/sheddable_request_filter.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#772 feat(conformance): Add initial InferencePool tests and shared Gateway setup
  conformance/conformance.go
  conformance/embed.go
  conformance/resources/manifests/manifests.yaml
  conformance/tests/basic/inferencepool_accepted.yaml
  conformance/utils/kubernetes/helpers.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#768 Add prefix cache aware scheduling
  cmd/epp/main.go
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/prefix_indexer_hit_bytes_metric
  pkg/epp/metrics/testdata/prefix_indexer_hit_ratio_metric
  pkg/epp/metrics/testdata/prefix_indexer_size_metric
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/prefix/indexer.go
  pkg/epp/scheduling/plugins/prefix/indexer_test.go
  pkg/epp/scheduling/plugins/prefix/plugin.go
  pkg/epp/scheduling/plugins/prefix/plugin_test.go
  pkg/epp/scheduling/plugins/scorer/kvcache.go
  pkg/epp/scheduling/plugins/scorer/queue.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#819 merge functions in env utils
  pkg/epp/util/env/env.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#818 generalize scheduling cycle state concept
  pkg/epp/scheduling/plugins/prefix/plugin.go
  pkg/epp/scheduling/plugins/prefix/plugin_test.go
  pkg/epp/scheduling/types/cycle_state.go
  pkg/epp/scheduling/types/scheduling_context.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#782 remove Model field from LLMRequest
  pkg/epp/requestcontrol/director.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/plugins/prefix/plugin.go
  pkg/epp/scheduling/plugins/prefix/plugin_test.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#800 feat: Add support to invoke PostResponse plugins
  cmd/epp/main.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/server.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/prefix/plugin_test.go
  pkg/epp/scheduling/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/plugins/scorer/queue_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/scheduling_context.go
  pkg/epp/scheduling/types/types.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#602 Add prefix aware request scheduling proposal
  docs/proposals/0602-prefix-cache-aware-routing-proposal/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#823 Docs: Bumps Kgateway to v2.0.2
  config/manifests/gateway/kgateway/httproute.yaml
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#822 renamed Metrics to MetricsState and move to a separate file
  pkg/epp/backend/metrics/fake.go
  pkg/epp/backend/metrics/metrics.go
  pkg/epp/backend/metrics/metrics_state.go
  pkg/epp/backend/metrics/metrics_test.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/metrics/collectors/inference_pool_test.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/plugins/scorer/queue_test.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#817 feat: Add build reference to the info metrics
  Dockerfile
  Makefile
  cloudbuild.yaml
  pkg/epp/metrics/metrics.go
  site-src/guides/metrics.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#808 Introduce SaturationDetector component
  pkg/epp/common/config/defaults.go
  pkg/epp/saturationdetector/config.go
  pkg/epp/saturationdetector/saturationdetector.go
  pkg/epp/saturationdetector/saturationdetector_test.go
  pkg/epp/scheduling/config/config.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#798 support extracting prompt from chat completions API
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/util/request/body.go
  pkg/epp/util/request/body_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#824 Fix Test Flakiness by adding short sleep in TestMetricsRefresh
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/backend/metrics/types.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#795 chore(conformance): Add timeout configuration
  conformance/conformance.go
  conformance/tests/basic/inferencepool_accepted.go
  conformance/utils/config/timing.go
  conformance/utils/kubernetes/helpers.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#603 Scheduler subsystem high level design proposal
  docs/proposals/006-scheduler/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#831 Updating top level readme
  README.md
  site-src/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#829 docs: roll out guide
  mkdocs.yml
  site-src/guides/adapter-rollout.md
  site-src/guides/inferencepool-rollout.md
  site-src/guides/replacing-inference-pool.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#842 reduce log level of "prefix cached servers" to TRACE
  pkg/epp/scheduling/plugins/prefix/plugin.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#755 add regression testing docs
  config/manifests/regression-testing/inferencemodel.yaml
  config/manifests/regression-testing/multi-lora-regression.yaml
  config/manifests/regression-testing/single-workload-regression.yaml
  config/manifests/regression-testing/vllm/multi-lora-deployment.yaml
  mkdocs.yml
  site-src/performance/benchmark/index.md
  site-src/performance/regression-testing/index.md
  tools/benchmark/benchmark.ipynb
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#844 fixed log before picker
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#837 Reorganize scheduling plugins
  cmd/epp/main.go
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/README.md
  pkg/epp/scheduling/plugins/multi/prefix/indexer.go
  pkg/epp/scheduling/plugins/multi/prefix/indexer_test.go
  pkg/epp/scheduling/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/plugins/multi/prefix/plugin_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#850 updated godoc on scheduler filters, pickers and prefix plugin
  pkg/epp/scheduling/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/plugins/filter/sheddable_capacity_filter.go
  pkg/epp/scheduling/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/plugins/picker/random_picker.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#849 Fix: Ignore header order in hermetic test
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#855 Updating readme to reflect llm-d collab!
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#857 fix: typo ('endpoing' -> 'endpoint')
  site-src/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#858 Updating readme wording
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#847 adding logging & support for better Client response
  pkg/epp/handlers/server.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#859 Adding util func for splitting large bodies into chunks
  pkg/epp/handlers/server.go
  pkg/epp/handlers/server_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#835 Scheduler config refactor for simplifying plugins registration
  cmd/epp/main.go
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/plugins/scorer/kvcache.go
  pkg/epp/scheduling/plugins/scorer/queue.go
  pkg/epp/scheduling/plugins/scorer/weighted_scorer.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_config.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/scheduling_context.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#860 Chunk implementation
  pkg/epp/handlers/request.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/server_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#728 feat: merge two metric servers
  cmd/bbr/main.go
  cmd/epp/main.go
  pkg/bbr/handlers/request_test.go
  pkg/bbr/metrics/metrics.go
  pkg/epp/metrics/collectors/inference_pool.go
  pkg/epp/metrics/collectors/inference_pool_test.go
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/server/controller_manager.go
  pkg/epp/util/metrics/metrics.go
  test/integration/epp/hermetic_test.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL

#812 docs: added examples to address various generative AI application scenarios by using gateway api inference extension
  mkdocs.yml
  site-src/guides/serve-multiple-genai-models.md
  site-src/guides/serve-multiple-lora-adapters.md
  site-src/images/serve-LoRA-adapters.png
  site-src/images/serve-mul-gen-AI-models.png
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#867 docs: Update link to Slack channel
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#862 Multi cycle scheduler
  cmd/epp/main.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/README.md
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/sheddable_capacity_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/indexer.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/indexer_test.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/profile-picker/all_profiles_picker.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/framework/plugins/scorer/queue_test.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/framework/weighted_scorer.go
  pkg/epp/scheduling/plugins/README.md
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_config.go
  pkg/epp/scheduling/scheduler_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#832 feat(conformance): tests for inferencepool_resolvedrefs_condition
  conformance/resources/manifests/manifests.yaml
  conformance/tests/basic/inferencepool_accepted.go
  conformance/tests/basic/inferencepool_resolvedrefs_condition.go
  conformance/tests/basic/inferencepool_resolvedrefs_condition.yaml
  conformance/utils/kubernetes/helpers.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#876 remove the PreCycle plugin from scheduler
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/scheduler_plugin_processing_latencies_metric
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#890 updated controller-runtime to v0.21.0 and its dependencies
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/api/v1alpha2/api_client.go
  client-go/informers/externalversions/api/v1alpha2/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha2/inferencepool.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm
