Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-01, with the labels that each got.

#139 Update README: Add Hugging Face Token Setup Instructions and Improve Deployment Instructions
  pkg/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#143 Updates APIs Based on Kubernetes API Conventions
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/inferencepool_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  config/samples/gateway_v1alpha1_inferencemodel.yaml
  config/samples/gateway_v1alpha1_inferencepool.yaml
  examples/poc/manifests/inferencepool-with-model.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#147 Fix InferencePoolReconciler
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#156 Updating the boilerplate template and regenerating
  api/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodel.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodelspec.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodelstatus.go
  client-go/applyconfiguration/api/v1alpha1/inferencepool.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolspec.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolstatus.go
  client-go/applyconfiguration/api/v1alpha1/poolobjectreference.go
  client-go/applyconfiguration/api/v1alpha1/targetmodel.go
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/doc.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/doc.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/doc.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/doc.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencepool.go
  client-go/clientset/versioned/typed/api/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/interface.go
  client-go/informers/externalversions/api/v1alpha1/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/v1alpha1/interface.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/listers/api/v1alpha1/expansion_generated.go
  client-go/listers/api/v1alpha1/inferencemodel.go
  client-go/listers/api/v1alpha1/inferencepool.go
  hack/boilerplate.go.txt
Labels: cncf-cla: yes, approved, lgtm, size/M

#160 Updating non-generated docs/ minor formatting
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/inferencepool_types.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#161 .*: change llm-instance-gateway -> gateway-api-inference-extension
  PROJECT
  README.md
  client-go/applyconfiguration/api/v1alpha1/inferencemodelspec.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolspec.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencepool.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/interface.go
  client-go/informers/externalversions/api/v1alpha1/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/v1alpha1/interface.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/listers/api/v1alpha1/inferencemodel.go
  client-go/listers/api/v1alpha1/inferencepool.go
  go.mod
  hack/update-codegen.sh
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/endpointslice_reconcilier_test.go
  pkg/ext-proc/backend/fake.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/backend/vllm/metrics_test.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/filter_test.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/test/benchmark/benchmark.go
  pkg/ext-proc/test/hermetic_test.go
  pkg/ext-proc/test/utils.go
  pkg/manifests/ext_proc.yaml
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#152 Changes InferencePool EPP Flags
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/main.go
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#165 ext-proc: remove unused fields from EndpointSliceReconciler
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#168 ext-proc/backend: add unit test for InferencePoolReconciler
  pkg/ext-proc/backend/inferencepool_reconciler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#172 ext-proc: change Inference* APIs to use NamespacedName
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler_test.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
  pkg/ext-proc/main.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#180 manifests: remove unused curl image from EPP manifest
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#179 Add a few debug logs
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/inferencepool_reconciler.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#148 Adds Health gRPC Server and Refactors Main()
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/health.go
  pkg/ext-proc/main.go
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#129 Adding some initial docs content and diagrams
  Makefile
  crd-ref-docs.yaml
  go.mod
  go.sum
  mkdocs.yml
  site-src/api-types/inferencepool.md
  site-src/concepts/conformance.md
  site-src/concepts/glossary.md
  site-src/concepts/use-cases.md
  site-src/contributing/index.md
  site-src/faq.md
  site-src/images/inferencepool-vs-service.png
  site-src/images/request-flow.png
  site-src/images/resource-model.png
  site-src/implementations.md
  site-src/index.md
  site-src/reference/spec.md
  site-src/stylesheets/extra.css
  tools/tools.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#195 Fixing Netlify builds
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#186 [v0.1 API Review] Grammatical fixes and TypedCondition creation/defaulting
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/inferencepool_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#182 Add logging guidelines
  README.md
  docs/dev.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#205 dev: respect the IMAGE args in Makefile
  Dockerfile
  Makefile
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#206 fix small typo
  site-src/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#177 Adding metrics for request total, latency and size
  go.mod
  go.sum
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/main.go
  pkg/ext-proc/metrics/README.md
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/metrics/testdata/request_duration_seconds_metric
  pkg/ext-proc/metrics/testdata/request_sizes_metric
  pkg/ext-proc/metrics/testdata/request_total_metric
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#185 [v0.1 API Review] Cleaning up optional fields/clearer wording
  api/v1alpha1/inferencemodel_types.go
  api/v1alpha1/inferencepool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  docs/proposals/002-api-proposal/proposal.md
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/datastore_test.go
  pkg/ext-proc/test/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#215 Add link to meeting notes
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#203 Adding new maintainers
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, do-not-merge/invalid-owners-file, approved, lgtm, size/M

#218 Adding myself & ahg-g to owners directly while we figure out alias bug
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm

#216 only print out pods & metrics when log level is DEBUG
  pkg/ext-proc/backend/provider.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#220 Alias fix
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, lgtm, size/S

#200 Separates EnvoyExtensionPolicy from Ext Proc
  pkg/README.md
  pkg/manifests/ext_proc.yaml
  pkg/manifests/extension_policy.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#214 [Metrics] Add input/output token and request size metrics
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/metrics/README.md
  pkg/ext-proc/metrics/metrics.go
  pkg/ext-proc/metrics/metrics_test.go
  pkg/ext-proc/metrics/testdata/input_tokens_metric
  pkg/ext-proc/metrics/testdata/output_tokens_metric
  pkg/ext-proc/metrics/testdata/response_sizes_metric
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#226 Update to k8s v0.32.0 and runtime to v0.20.0
  client-go/applyconfiguration/api/v1alpha1/inferencemodel.go
  client-go/applyconfiguration/api/v1alpha1/inferencemodelspec.go
  client-go/applyconfiguration/api/v1alpha1/inferencepool.go
  client-go/applyconfiguration/api/v1alpha1/inferencepoolspec.go
  client-go/applyconfiguration/internal/internal.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/typed/api/v1alpha1/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_api_client.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/fake/fake_inferencepool.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/api/v1alpha1/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha1/inferencepool.go
  client-go/informers/externalversions/generic.go
  client-go/listers/api/v1alpha1/inferencemodel.go
  client-go/listers/api/v1alpha1/inferencepool.go
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL

#221 Slight cleanup of some of our readmes
  README.md
  examples/placeholder.md
  pkg/README.md
  pkg/manifests/gateway/enable_patch_policy.yaml
  pkg/manifests/gateway/extension_policy.yaml
  pkg/manifests/gateway/gateway.yaml
  pkg/manifests/gateway/patch_policy.yaml
  pkg/manifests/gateway/traffic_policy.yaml
  pkg/manifests/inferencepool-with-model.yaml
  pkg/manifests/vllm/vllm-lora-deployment.yaml
  pkg/scheduling.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#233 More Getting Started updates
  pkg/README.md
  pkg/manifests/ext_proc.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#236 Adding logging const and updating usage
  pkg/ext-proc/backend/datastore.go
  pkg/ext-proc/backend/endpointslice_reconciler.go
  pkg/ext-proc/backend/inferencemodel_reconciler.go
  pkg/ext-proc/backend/provider.go
  pkg/ext-proc/backend/vllm/metrics.go
  pkg/ext-proc/handlers/request.go
  pkg/ext-proc/handlers/response.go
  pkg/ext-proc/handlers/server.go
  pkg/ext-proc/scheduling/filter.go
  pkg/ext-proc/scheduling/scheduler.go
  pkg/ext-proc/util/logging/logging_const.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#241 Fixes gomega.Eventually() in e2e Test
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/testdata/client.yaml
  test/testdata/envoy.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#164 Add Endpoint Picker Protocol Proposal
  docs/proposals/003-model-server-protocol/protocol.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#242 Docker modification to support simple `docker build`
  Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#222 Refactor ext-proc Main with Server Package Add Hermetic Test with k8s API Client for EPP
  pkg/ext-proc/main.go
  pkg/ext-proc/server/runserver.go
  pkg/ext-proc/test/hermetic_test.go
  test/integration/hermetic_test.go
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#248 Requeue reconcile requests for endpointslice until the inferencepool is available
  pkg/ext-proc/backend/endpointslice_reconciler.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#255 Repo cleanup
  pkg/manifests/ext_proc.yaml
  tools/simulations/llm_ig_simulation/src/__init__.py
  tools/simulations/llm_ig_simulation/src/benchmark_one_server.py
  tools/simulations/llm_ig_simulation/src/constants.py
  tools/simulations/llm_ig_simulation/src/continous_batching.py
  tools/simulations/llm_ig_simulation/src/llmactor.py
  tools/simulations/llm_ig_simulation/src/loadbalancer.py
  tools/simulations/llm_ig_simulation/src/main.py
  tools/simulations/llm_ig_simulation/src/request.py
  tools/simulations/llm_inference_gateway_simulation.ipynb
Labels: cncf-cla: yes, size/XS, approved, lgtm

#246 Fix e2e test
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#261 inferencemodel_reconciler: Fix a log message
  pkg/ext-proc/backend/inferencemodel_reconciler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#254 Populating api-types & concepts
  site-src/api-types/inferencemodel.md
  site-src/api-types/inferencepool.md
  site-src/concepts/api-overview.md
  site-src/concepts/roles-and-personas.md
  site-src/images/inference-overview.svg
  site-src/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm
