Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-06, with the labels that each got.

#903 docs: update Istio gateway name for consistency
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#883 chor(conformance): fix header and remove extra comments
  conformance/tests/basic/inferencepool_resolvedrefs_condition.go
  conformance/utils/traffic/traffic.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#900 Tools: Fixes test-e2e.sh script
  hack/test-e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#761 Amend the endpoint picker protocol to support multiple fallback endpoints
  docs/proposals/004-endpoint-picker-protocol/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#889 remove SchedulingContext, flatten scheduler interfaces
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/sheddable_capacity_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/framework/plugins/scorer/queue_test.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/scheduling_context.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#906 Update the Cleanup section for Istio in Getting Started
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#805 Refactor: Externalize Scheduler's saturation logic and criticality-based service differentiation
  cmd/epp/main.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/saturationdetector/saturationdetector.go
  pkg/epp/saturationdetector/saturationdetector_test.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#898 Adds vLLM Simulator Support
  Makefile
  config/manifests/vllm/sim-deployment.yaml
  site-src/guides/index.md
  test/e2e/epp/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#913 fixed typo in makefile
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#916 added GetEnvBool function and unit-tests
  cmd/epp/main.go
  pkg/epp/util/env/env.go
  pkg/epp/util/env/env_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#914 move PostResponse plugins to requestcontrol instead of scheduler
  cmd/epp/main.go
  pkg/epp/handlers/server.go
  pkg/epp/metrics/metrics.go
  pkg/epp/plugins/plugins.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/requestcontrol/plugins.go
  pkg/epp/requestcontrol/types.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#919 renamed interface from PostResponsePlugin to PostResponse
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/plugins.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#924 Add the option to specify epp env vars in helm chart
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#921 remove Critical boolean from scheduling request
  pkg/epp/requestcontrol/director.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#923 Add prefix cache plugin configuration guide
  mkdocs.yml
  site-src/guides/epp-configuration/prefix-aware.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#926 added context argument to scheduling profile picker
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/profile-picker/all_profiles_picker.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#922 feat(Conformance): Add a header based filter to make a controllable epp behavior determined by request header.
  Dockerfile
  cmd/epp/main.go
  conformance/testing-epp/plugins/filter/filter_test.go
  conformance/testing-epp/plugins/filter/request_header_based_filter.go
  conformance/testing-epp/scheduler.go
  conformance/testing-epp/sheduler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#931 Docs: Fixes Meeting Recording Link
  site-src/contributing/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#912 metrics: Add documentation for sample alert rules
  site-src/guides/metrics.md
  tools/alerts/alert.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#941 Changes to multi-model guide in documentation
  site-src/guides/serve-multiple-genai-models.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#891 docs: use inference gateway terminology
  site-src/concepts/api-overview.md
  site-src/guides/index.md
  site-src/guides/serve-multiple-genai-models.md
  site-src/guides/serve-multiple-lora-adapters.md
  site-src/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#937 scheduler redesign continuation
  cmd/epp/main.go
  conformance/testing-epp/scheduler.go
  conformance/testing-epp/sheduler_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_config.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#954 fix: Mark alert block as yaml to fix syntax error
  site-src/guides/metrics.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#948 docs: Try to polish the go doc comments for InferenceModelSpec
  api/v1alpha2/inferencemodel_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  docs/proposals/002-api-proposal/README.md
  site-src/reference/spec.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#956 moved main code to runner package under epp/cmd
  Dockerfile
  cmd/epp/main.go
  cmd/epp/runner/health.go
  cmd/epp/runner/runner.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/requestcontrol/request_control_config.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#978 Add scripts for running e2es
  Makefile
  hack/run-e2es.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#974 Bump Istio tag reference
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#991 API: Adds 5xx Status Code for Invalid ExtRef
  api/v1alpha2/inferencepool_types.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#959 feat(conformance): Add test for invalid EPP service reference
  conformance/tests/basic/inferencepool_invalid_epp_service.go
  conformance/tests/basic/inferencepool_invalid_epp_service.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#995 moved the creation of the context to main.go.
  cmd/epp/main.go
  cmd/epp/runner/runner.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#989 doc: fix dead links
  site-src/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#966 feat: add health check for epp cluster
  cmd/epp/runner/runner.go
  pkg/epp/server/runserver.go
  test/testdata/envoy.yaml
  test/testdata/inferencepool-e2e.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#820 test: gRPC server unit tests and utilities for further end-to-end tests
  pkg/epp/server/server_test.go
  test/utils/server.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#980 Update dynamic-lora-sidecar to expose metrics to track loaded adapters
  site-src/guides/metrics.md
  tools/dynamic-lora-sidecar/README.md
  tools/dynamic-lora-sidecar/deployment.yaml
  tools/dynamic-lora-sidecar/requirements.txt
  tools/dynamic-lora-sidecar/sidecar/sidecar.py
  tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#834 feat(conformance): Add HTTPRouteMultipleRulesDifferentPools test
  conformance/resources/manifests/manifests.yaml
  conformance/tests/basic/inferencepool_multiple_rules_different_pools.go
  conformance/tests/basic/inferencepool_multiple_rules_different_pools.yaml
  conformance/utils/config/timing.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/traffic/traffic.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1004 adding pre-request plugin to requestcontrol layer
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/plugins.go
  pkg/epp/requestcontrol/request_control_config.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#878 feat(conformance): Add test execution instruction to the guide.
  conformance/reports/README.md
  mkdocs.yml
  site-src/guides/conformance-tests.md
  site-src/guides/implementers.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#911 feat(conformance): Add HTTPRoute port validation tests for InferencePool backends
  conformance/tests/basic/inferencepool_httproute_port_validation.go
  conformance/tests/basic/inferencepool_httproute_port_validation.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#984 fix(Conformance): Add namespace-(labels|annotations) flag parsing
  conformance/conformance.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1020 Adds vLLM CPU and Sim Support to Release Script
  .github/ISSUE_TEMPLATE/new-release.md
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#1021 Add Makefile to run unit tests of tools/dynamic-lora-sidecar locally
  tools/dynamic-lora-sidecar/Dockerfile
  tools/dynamic-lora-sidecar/Makefile
  tools/dynamic-lora-sidecar/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1013 profile handler ProcessResult returns additional return value
  pkg/epp/common/config/configloader_test.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#1012 cleanup after config api PR was merged
  cmd/epp/main.go
  cmd/epp/runner/register.go
  cmd/epp/runner/runner.go
  pkg/epp/registry/registry.go
  pkg/epp/requestcontrol/request_control_config.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_config.go
  pkg/epp/scheduling/scheduler_config_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1024 Making inferenceModel optional
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#596 Adding Design Principles
  mkdocs.yml
  site-src/concepts/design-principles.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#1027 Backport PR 978 Add scripts for running e2es (#978)
  Makefile
  hack/run-e2es.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#1026 Adding Nir as a maintainer!
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1029 Backport: PR 1020- Adds vLLM CPU and Sim Support to Release Script
  .github/ISSUE_TEMPLATE/new-release.md
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#830 API: Adds default status condition to InferencePool
  api/v1alpha2/inferencepool_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#961 feat(conformance): Add EPP conformance test for Gateway routing
  conformance/conformance.go
  conformance/resources/manifests/manifests.yaml
  conformance/tests/basic/gateway_following_epp_routing.go
  conformance/tests/basic/gateway_following_epp_routing.yaml
  conformance/utils/config/timing.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/traffic/traffic.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1041 update sim deployment tag to latest
  config/manifests/vllm/sim-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1038 refactor: rename plugin.Name() => plugin.Type()
  cmd/epp/runner/register.go
  conformance/testing-epp/plugins/filter/request_header_based_filter.go
  docs/proposals/0845-scheduler-architecture-proposal/interfaces/interface.go
  pkg/epp/common/config/configloader_test.go
  pkg/epp/plugins/plugins.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_config_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1045 docs: update the Getting Started guide to use the latest CRDs
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1040 added cycle state to pick & process results in profile handler
  conformance/testing-epp/plugins/filter/filter_test.go
  conformance/testing-epp/plugins/filter/request_header_based_filter.go
  pkg/epp/common/config/configloader_test.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/framework/plugins/scorer/queue_test.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#838 feat(conformance): Add HTTPRouteMultipleGatewaysDifferentPools test
  conformance/tests/basic/httproute_multiple_gateways_different_pools.go
  conformance/tests/basic/httproute_multiple_gateways_different_pools.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1039 Add APIs for the instantiated plugins to the EPP Handle
  cmd/epp/runner/register.go
  cmd/epp/runner/runner.go
  pkg/epp/common/config/loader/configloader.go
  pkg/epp/common/config/loader/configloader_test.go
  pkg/epp/plugins/plugins.go
  pkg/epp/scheduling/scheduler_config.go
  pkg/epp/scheduling/scheduler_config_test.go
  test/utils/handle.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1034 refactor(confromance) use common resources for `InferencePoolHTTPRoutePortValidation` test
  conformance/tests/basic/inferencepool_httproute_port_validation.go
  conformance/tests/basic/inferencepool_httproute_port_validation.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test, gie-area/conformance

#1057 Reintroduce Plugin.Name()
  api/config/v1alpha1/defaults.go
  api/config/v1alpha1/endpointpickerconfig_types.go
  conformance/testing-epp/plugins/filter/request_header_based_filter.go
  pkg/epp/common/config/loader/configloader.go
  pkg/epp/common/config/loader/configloader_test.go
  pkg/epp/plugins/plugins.go
  pkg/epp/plugins/registry.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/least_kvcache_filter.go
  pkg/epp/scheduling/framework/plugins/filter/least_queue_filter.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/plugins/profile/single_profile_handler.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  test/testdata/configloader_1_test.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1023 Extensible/Pluggable data layer proposal
  docs/proposals/1023-data-layer-architecture/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1064 docs: added gke clean up instructions
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#997 feat(flowcontrol): Add Foundational Types and Architecture
  pkg/epp/flowcontrol/README.md
  pkg/epp/flowcontrol/types/README.md
  pkg/epp/flowcontrol/types/errors.go
  pkg/epp/flowcontrol/types/flow.go
  pkg/epp/flowcontrol/types/outcomes.go
  pkg/epp/flowcontrol/types/request.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test, gie-area/flowcontrol

#1063 refactor: Allow export prefix SchedulingContextState for use across plugins
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/types/cycle_state.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1053 feat: Added a factory function for the DecisionTree filter
  cmd/epp/runner/register.go
  cmd/epp/runner/runner.go
  pkg/epp/scheduling/framework/plugins/filter/decision_tree_filter.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1069 Adding pprof endpoints to metrics port
  cmd/epp/runner/runner.go
  mkdocs.yml
  site-src/guides/metrics-and-observability.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#1077 Update model server protocol with prefix cache reuse
  docs/proposals/003-model-server-protocol/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#1078 Update prefix plugin guide to use vllm as default to be consistent
  site-src/guides/epp-configuration/prefix-aware.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1055 refactor(conformance) merge similar utility functions.
  conformance/tests/basic/epp_unavailable_fail_open.go
  conformance/tests/basic/gateway_following_epp_routing.go
  conformance/tests/basic/inferencepool_httproute_port_validation.go
  conformance/tests/basic/inferencepool_multiple_rules_different_pools.go
  conformance/tests/basic/inferencepool_resolvedrefs_condition.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/traffic/traffic.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1060 fix(conformance): fix conformance setup issue by not relying on `suite.Setup` from gateway-api
  conformance/conformance.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#988 e2e cleanup
  Makefile
  hack/run-e2es.sh
  hack/test-e2e.sh
  test/e2e/epp/e2e_suite_test.go
  test/testdata/inferencepool-e2e.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#1070 API: Refine ResolvedRefs condition for invalid ExtensionReference and expand InferencePoolReason values
  api/v1alpha2/inferencepool_types.go
  docs/proposals/002-api-proposal/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1087 Tidy up Data Layer documentation
  docs/proposals/1023-data-layer-architecture/README.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1052 test(epp): add unit tests for error package
  pkg/epp/util/error/error_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test, kind/cleanup

#1088 convert subset filter from a plugin to logic in director
  cmd/epp/runner/runner.go
  conformance/testing-epp/scheduler_test.go
  pkg/bbr/handlers/server.go
  pkg/epp/backend/metrics/metrics_state.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/response_test.go
  pkg/epp/handlers/server.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/subsetting_filter.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/types/cycle_state.go
  pkg/epp/scheduling/types/types.go
  pkg/epp/util/error/error.go
  pkg/epp/util/error/error_test.go
  pkg/epp/util/logging/fatal.go
  pkg/epp/util/request/body.go
  pkg/epp/util/request/body_test.go
  pkg/epp/util/request/metadata_test.go
  test/integration/epp/hermetic_test.go
  test/integration/util.go
Labels: cncf-cla: yes, approved, lgtm, size/XL
