Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-07, with the labels that each got.

#1103 Add unit tests for picker plugin
  pkg/epp/scheduling/framework/plugins/picker/picker_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1108 Upper case `Inference` in `metrics.RecordInferencePoolReadyPods` for consistency
  pkg/epp/backend/metrics/logger.go
  pkg/epp/metrics/metrics.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1112 fixed sim deployment for e2e tests
  config/manifests/vllm/sim-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1111 verify fallback to default values if parameters are not defined in config file
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1114 minor refactor to config loading from file/text
  cmd/epp/runner/runner.go
  pkg/epp/common/config/loader/configloader.go
  pkg/epp/common/config/loader/configloader_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1113 minor updates to typed-name
  pkg/epp/plugins/typedname.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1059 handle picking multiple destinations in scheduling layer
  cmd/epp/runner/runner.go
  conformance/testing-epp/scheduler.go
  conformance/testing-epp/scheduler_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/plugins/picker/common.go
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/picker_test.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1085 Clarify that connections to EPP should use TLS by default
  api/v1alpha2/inferencepool_types.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1131 feat(conformance): loose the InferencePoolInvalidEPPService to only check httpRoute is accepted true.
  conformance/tests/basic/inferencepool_invalid_epp_service.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1142 Fix makefile: test-integration
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1155 removed unused config/manager dir
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1159 adds flag to disble pprof if desired, defaulted on
  cmd/epp/runner/runner.go
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/values.yaml
  pkg/epp/server/runserver.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1152 load plugins from file in conformance tests
  Dockerfile
  cmd/epp/runner/register.go
  cmd/epp/runner/runner.go
  conformance/resources/manifests/manifests.yaml
  conformance/testing-epp/scheduler.go
  conformance/testing-epp/scheduler_test.go
  pkg/epp/scheduling/framework/plugins/test/README.md
  pkg/epp/scheduling/framework/plugins/test/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/test/filter/request_header_based_filter.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1153 remove NewScheduler function
  cmd/epp/runner/runner.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1157 removed USE_STREAMING env var from conformance + tests
  conformance/resources/manifests/manifests.yaml
  test/testdata/inferencepool-e2e.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1139 feat: Introduce pluggable intra-flow dispatch policy framework
  pkg/epp/flowcontrol/framework/doc.go
  pkg/epp/flowcontrol/framework/mocks/mocks.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/README.md
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/factory.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs_test.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/functional_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/README.md
  pkg/epp/flowcontrol/framework/plugins/queue/factory.go
  pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go
  pkg/epp/flowcontrol/framework/policies.go
  pkg/epp/flowcontrol/framework/queue.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1182 fix: set epp image tag when releasing
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/S

#1186 Update istio release
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1174 feat(flowcontrol): Introduce ManagedQueue and Service Contracts
  pkg/epp/flowcontrol/README.md
  pkg/epp/flowcontrol/contracts/registry.go
  pkg/epp/flowcontrol/framework/errors.go
  pkg/epp/flowcontrol/framework/mocks/mocks.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/README.md
  pkg/epp/flowcontrol/framework/plugins/queue/README.md
  pkg/epp/flowcontrol/framework/plugins/queue/benchmark_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/factory.go
  pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/listqueue/listqueue.go
  pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap.go
  pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap_test.go
  pkg/epp/flowcontrol/framework/policies.go
  pkg/epp/flowcontrol/framework/queue.go
  pkg/epp/flowcontrol/registry/managedqueue.go
  pkg/epp/flowcontrol/registry/managedqueue_test.go
  pkg/epp/flowcontrol/types/flow.go
  pkg/epp/flowcontrol/types/request.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#1184 chore: update vllm deployment tag to latest
  config/manifests/vllm/cpu-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1143 Add an "Implementing a Compatible Data Plane" section to the implementers guide
  site-src/guides/implementers.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1191 feat(flowcontrol): refine types and consolidate docs
  pkg/epp/flowcontrol/types/README.md
  pkg/epp/flowcontrol/types/doc.go
  pkg/epp/flowcontrol/types/errors.go
  pkg/epp/flowcontrol/types/flow.go
  pkg/epp/flowcontrol/types/mocks/mocks.go
  pkg/epp/flowcontrol/types/outcomes.go
  pkg/epp/flowcontrol/types/request.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1193 docs: update to use kebab-cased flags changed at #1177
  pkg/epp/server/runserver.go
  site-src/guides/epp-configuration/config-text.md
  site-src/guides/index.md
  site-src/guides/inferencepool-rollout.md
  site-src/implementations/model-servers.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1198 added graceful shutdown when scheduler config is not initialized
  cmd/epp/runner/runner.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1206 removed cmd/registry file
  cmd/epp/main.go
  cmd/epp/runner/register.go
  cmd/epp/runner/runner.go
  pkg/epp/plugins/handle.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1190 Support scraping metrics from target running with TLS
  cmd/epp/runner/runner.go
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/values.yaml
  pkg/epp/backend/metrics/metrics.go
  pkg/epp/backend/metrics/metrics_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1005 gke-gateway v0.5.0 conformance test report 9/9
  conformance/reports/v0.5.0/gateway/gke-gateway/README.md
  conformance/reports/v0.5.0/gateway/gke-gateway/standard-v1.32.4-rxlb-gateway-report.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test, gie-area/conformance

#1218 added join slack badge to readme
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1140 chore: 🔨 Use the v0.3.0 llm-d-inference-sim image tag.
  .github/ISSUE_TEMPLATE/new-release.md
  config/manifests/vllm/sim-deployment.yaml
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1196 release issue template: updated the tag command to include the -s for signing the tag
  .github/ISSUE_TEMPLATE/new-release.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1225 Update index.md with gateway-inference-extension slack
  site-src/contributing/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1230 fix: missing permission to list inference.networking.k8s.io/v1/inferencepool
  config/manifests/inferencepool-resources.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1199 Proposing the successor to the InferenceModel API
  docs/proposals/1199-inferencemodel-api-evolution/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#1233 cleanup of unused fields and functions
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/requestcontrol/request_control_config.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/scorer/kvcache.go
  pkg/epp/scheduling/framework/plugins/scorer/queue.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/types/cycle_state.go
  pkg/epp/server/runserver.go
  pkg/epp/util/testing/diff.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#1216 chore: update CRD BundleVersion to main-dev
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencemodels.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  version/version.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1239 Change String() to accept a value reciever.
  pkg/epp/plugins/typedname.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1234 Add nightly benchmarking documentation
  site-src/performance/regression-testing/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1235 updated metrics and logging for plugins
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/plugin_processing_latencies_metric
  pkg/epp/metrics/testdata/scheduler_plugin_processing_latencies_metric
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/plugins.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1263 cleanup of config from scheduling package
  cmd/epp/runner/runner.go
  pkg/epp/common/config/defaults.go
  pkg/epp/config/loader/configloader.go
  pkg/epp/config/loader/configloader_test.go
  pkg/epp/saturationdetector/config.go
  pkg/epp/scheduling/config/config.go
  pkg/epp/scheduling/framework/plugins/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/filter/lora_affinity_filter.go
  pkg/epp/scheduling/framework/plugins/filter/low_queue_filter.go
  pkg/epp/scheduling/scheduler_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1010 Add support for multi platform image
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1071 fix: split EPP RBAC into cluster and namespaced scoped permission
  config/charts/inferencepool/templates/rbac.yaml
  config/manifests/inferencepool-resources.yaml
  test/e2e/epp/e2e_suite_test.go
  test/testdata/inferencepool-e2e.yaml
  test/utils/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-action-required

#1255 Renaming InferenceModel to InferenceObjectives
  PROJECT
  apix/v1alpha2/inferenceobjective_types.go
  apix/v1alpha2/zz_generated.deepcopy.go
  apix/v1alpha2/zz_generated.register.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjective.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjectivespec.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjectivestatus.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/typed/apix/v1alpha2/apix_client.go
  client-go/clientset/versioned/typed/apix/v1alpha2/fake/fake_apix_client.go
  client-go/clientset/versioned/typed/apix/v1alpha2/fake/fake_inferenceobjective.go
  client-go/clientset/versioned/typed/apix/v1alpha2/generated_expansion.go
  client-go/clientset/versioned/typed/apix/v1alpha2/inferencemodel.go
  client-go/clientset/versioned/typed/apix/v1alpha2/inferenceobjective.go
  client-go/informers/externalversions/apix/v1alpha2/inferenceobjective.go
  client-go/informers/externalversions/apix/v1alpha2/interface.go
  client-go/informers/externalversions/generic.go
  client-go/listers/apix/v1alpha2/expansion_generated.go
  client-go/listers/apix/v1alpha2/inferencemodel.go
  client-go/listers/apix/v1alpha2/inferenceobjective.go
  config/charts/inferencepool/templates/rbac.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  config/crd/kustomization.yaml
  config/manifests/inferenceobjective.yaml
  config/manifests/inferencepool-resources.yaml
  config/manifests/regression-testing/inferenceobjective.yaml
  conformance/conformance.go
  conformance/reports/v0.5.0/gateway/gke-gateway/README.md
  conformance/resources/manifests/manifests.yaml
  conformance/scripts/istio/Makefile
  conformance/tests/basic/epp_unavailable_fail_open.yaml
  conformance/tests/basic/gateway_following_epp_routing.yaml
  conformance/utils/assertions.go
  crd-ref-docs.yaml
  docs/dev.md
  pkg/epp/README.md
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferenceobjective_reconciler.go
  pkg/epp/controller/inferenceobjective_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/handlers/server.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/server/controller_manager.go
  pkg/epp/server/runserver.go
  pkg/epp/server/server_test.go
  pkg/epp/util/testing/wrappers.go
  test/e2e/epp/e2e_suite_test.go
  test/e2e/epp/e2e_test.go
  test/integration/epp/hermetic_test.go
  test/testdata/inferencepool-e2e.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
  test/utils/server.go
  test/utils/utils.go
  test/utils/wrappers.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL
