Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-03, with the labels that each got.

#430 Consistent validation for reference types
  api/v1alpha2/inferencemodel_types.go
  api/v1alpha2/inferencepool_types.go
  api/v1alpha2/shared_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1alpha2/extension.go
  client-go/applyconfiguration/api/v1alpha2/extensionreference.go
  client-go/applyconfiguration/api/v1alpha2/poolobjectreference.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/datastore/datastore.go
  pkg/epp/util/testing/wrappers.go
  test/utils/wrappers.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#431 create pods during integration tests
  pkg/epp/test/utils.go
  pkg/epp/util/testing/wrappers.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#433 fix typos
  docs/proposals/003-model-server-protocol/README.md
  docs/proposals/004-endpoint-picker-protocol/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#355 Add code for Envoy extension that supports body-to-header translation
  body-based-routing.Dockerfile
  cmd/body-based-routing/health.go
  cmd/body-based-routing/main.go
  pkg/body-based-routing/README.md
  pkg/body-based-routing/handlers/request.go
  pkg/body-based-routing/handlers/request_test.go
  pkg/body-based-routing/handlers/response.go
  pkg/body-based-routing/handlers/server.go
  pkg/body-based-routing/server/runserver.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#442 Add Makefile + cloudbuild configs for body-based routing extension
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#436 added cpu based example
  config/manifests/ext_proc.yaml
  config/manifests/inferencemodel.yaml
  config/manifests/vllm/cpu-deployment.yaml
  config/manifests/vllm/gpu-deployment.yaml
  site-src/guides/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#448 updated cleanup section in quickstart
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/S, needs-ok-to-test

#423 scheduling changes for lora affinity load balancing
  docs/proposals/003-model-server-protocol/README.md
  pkg/epp/backend/vllm/metrics.go
  pkg/epp/scheduling/filter.go
  pkg/epp/scheduling/filter_test.go
  pkg/epp/scheduling/scheduler.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#449 Fixing default status on InferencePool
  api/v1alpha2/inferencepool_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#429 Use server side namespace filter
  cmd/epp/main.go
  pkg/epp/controller/inferencemodel_reconciler.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/server/controller_manager.go
  pkg/epp/server/runserver.go
  test/integration/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#451 fixed filepath that points to gpu based model server deployment in few places
  hack/release-quickstart.sh
  site-src/guides/index.md
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#453 Add library for generating self-signed cert
  internal/tls/tls.go
  pkg/body-based-routing/server/runserver.go
  pkg/epp/server/runserver.go
Labels: cncf-cla: yes, size/L, approved, lgtm, needs-ok-to-test

#450 Support full duplex streaming
  cmd/epp/main.go
  config/manifests/ext_proc.yaml
  config/manifests/gateway/extension_policy.yaml
  config/manifests/gateway/patch_policy.yaml
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/server/runserver.go
Labels: approved, lgtm, cncf-cla: no, size/XL

#454 Renaming conditions and reasons used in InferencePool status
  api/v1alpha2/inferencepool_types.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#457 Move integration and e2e tests for epp into epp-specific directories
  test/e2e/epp/README.md
  test/e2e/epp/e2e_suite_test.go
  test/e2e/epp/e2e_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#458 Add initial integration test for body-based routing extension
  pkg/body-based-routing/server/runserver.go
  test/integration/bbr/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#460 Each pod has independent loops to refresh metrics
  Makefile
  cmd/epp/main.go
  pkg/epp/backend/fake.go
  pkg/epp/backend/metrics/fake.go
  pkg/epp/backend/metrics/logger.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/backend/provider.go
  pkg/epp/backend/provider_test.go
  pkg/epp/backend/vllm/metrics.go
  pkg/epp/backend/vllm/metrics_test.go
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/datastore/types.go
  pkg/epp/handlers/request.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/scheduling/filter.go
  pkg/epp/scheduling/filter_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/server/runserver.go
  pkg/epp/test/benchmark/benchmark.go
  pkg/epp/test/utils.go
  pkg/epp/util/testing/request.go
  pkg/epp/util/testing/wrappers.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#467 fixed broken link in README
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#477 [BBR] Fix bug where request trailers were not being handled
  pkg/body-based-routing/handlers/server.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#479 Add the base model to InferenceModel sample manifest
  config/manifests/inferencemodel.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#478 Fix metrics debug log; change metrics client log level to reduce spam
  pkg/epp/backend/metrics/fake.go
  pkg/epp/backend/metrics/logger.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/backend/vllm/metrics.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#481 Add the base model of the cpu vllm sample app to InferenceModel.yaml
  config/manifests/inferencemodel.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#484 Fix: Updates Docs for Sidecar Requirements
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#487 Switch default serving and health check ports for bbr
  cmd/body-based-routing/main.go
  pkg/body-based-routing/server/runserver.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#445 Amend the endpoint picker protocol to support fallbacks and subsetting
  docs/proposals/004-endpoint-picker-protocol/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#490 Update Makefile for BBR to ensure all proper tags are added
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#494 Improve response handling issues.
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#468 Add metrics for BBR extension
  cmd/body-based-routing/main.go
  pkg/body-based-routing/handlers/request.go
  pkg/body-based-routing/handlers/request_test.go
  pkg/body-based-routing/metrics/metrics.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#329 [Metrics] Add vLLM streaming support for metrics
  pkg/epp/handlers/response.go
  pkg/epp/handlers/response_test.go
  pkg/epp/handlers/server.go
  site-src/guides/metrics.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#485 added support for testing cpu example in e2e tests
  Makefile
  test/e2e/epp/e2e_suite_test.go
  test/e2e/epp/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#461 Redesign EPP Metrics Pipeline to be Model Server Agnostic
  cmd/epp/main.go
  pkg/epp/backend/metrics/metrics.go
  pkg/epp/backend/metrics/metrics_spec.go
  pkg/epp/backend/metrics/metrics_spec_test.go
  pkg/epp/backend/metrics/metrics_test.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/vllm/metrics.go
  pkg/epp/backend/vllm/metrics_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#501 Update GO version to 1.24
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#502 Fixing image build and adding image building to test runs
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#506 Refactor the integration tests setup
  test/integration/epp/hermetic_test.go
  test/integration/epp/test_suite.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#509 fix log line
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#512 update release version
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#511 switch to using formal vllm-cpu image
  config/manifests/vllm/cpu-deployment.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#508 Refactor beforeSuite in integration tests
  pkg/epp/server/controller_manager.go
  pkg/epp/util/testing/wrappers.go
  test/integration/epp/hermetic_test.go
  test/integration/epp/test_suite.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#524 Split the extension policy since it is envoy specific
  config/manifests/gateway/patch_policy.yaml
  config/manifests/inferencepool.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#527 Docs: Uses tabs for quickstart model server options
  mkdocs.yml
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#480 Add instructions to run benchmarks
  benchmark/README.md
  benchmark/benchmark.ipynb
  benchmark/download-benchmark-results.bash
  benchmark/requirements.txt
  config/manifests/benchmark/benchmark.yaml
  config/manifests/benchmark/model-server-service.yaml
  mkdocs.yml
  site-src/performance/benchmark/example-bar-chart.png
  site-src/performance/benchmark/index.md
Labels: cncf-cla: yes, approved, lgtm, size/XL

#416 add helm template
  config/charts/inferencepool/.helmignore
  config/charts/inferencepool/Chart.yaml
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/NOTES.txt
  config/charts/inferencepool/templates/_helpers.tpl
  config/charts/inferencepool/templates/inferencepool.yaml
  config/charts/inferencepool/templates/rbac.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#530 bump vllm-cpu image to latest
  config/manifests/vllm/cpu-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#531 fixed rbac in helm chart
  config/charts/inferencepool/templates/rbac.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#538 Simplifying EPP-side buffer
  pkg/epp/handlers/streamingserver.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#540 Add inferencepool chart push mechanics
  Makefile
  cloudbuild.yaml
  config/charts/inferencepool/Chart.yaml
  hack/push-chart.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#542 Updated the image used for cloudbuild
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#544 Simplify body streaming for BBR
  pkg/body-based-routing/handlers/server.go
Labels: cncf-cla: yes, approved, lgtm, size/S, needs-ok-to-test

#539 Bug fix: Initialize RequestReceivedTimestamp
  pkg/epp/handlers/streamingserver.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#518 [Metrics] Handle vLLM streaming response in streaming server
  pkg/epp/handlers/response.go
  pkg/epp/handlers/streamingserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#545 Add some more unit tests for BBR
  pkg/body-based-routing/handlers/server.go
  pkg/body-based-routing/handlers/server_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#547 Tag the main version of the helm chart with v0
  cloudbuild.yaml
  hack/push-chart.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#552 Default to streaming mode
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/inferencepool.yaml
  config/manifests/gateway/patch_policy.yaml
  config/manifests/inferencepool.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#546 Initial helm chart for bbr
  config/charts/body-based-routing/.helmignore
  config/charts/body-based-routing/Chart.yaml
  config/charts/body-based-routing/README.md
  config/charts/body-based-routing/templates/NOTES.txt
  config/charts/body-based-routing/templates/bbr.yaml
  config/charts/body-based-routing/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#553 Add makefile configs for bbr helm chart
  Makefile
  cloudbuild.yaml
  config/charts/body-based-routing/README.md
  hack/push-chart.sh
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#560 Adding deprecation notice of BUFFERED mode on patch policy.
  config/manifests/gateway/patch_policy.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#555 Allow bodyless requests to passthrough EPP
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/handlers/request.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/response_test.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/handlers/streamingserver_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#566 Update boilerplate template
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.register.go
  client-go/applyconfiguration/api/v1alpha2/endpointpickerconfig.go
  client-go/applyconfiguration/api/v1alpha2/extension.go
  client-go/applyconfiguration/api/v1alpha2/extensionconnection.go
  client-go/applyconfiguration/api/v1alpha2/extensionreference.go
  client-go/applyconfiguration/api/v1alpha2/inferencemodel.go
  client-go/applyconfiguration/api/v1alpha2/inferencemodelspec.go
  client-go/applyconfiguration/api/v1alpha2/inferencemodelstatus.go
  client-go/applyconfiguration/api/v1alpha2/inferencepool.go
  client-go/applyconfiguration/api/v1alpha2/inferencepoolspec.go
  client-go/applyconfiguration/api/v1alpha2/inferencepoolstatus.go
  client-go/applyconfiguration/api/v1alpha2/poolobjectreference.go
  client-go/applyconfiguration/api/v1alpha2/poolstatus.go
  client-go/applyconfiguration/api/v1alpha2/targetmodel.go
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/doc.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/doc.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/api/v1alpha2/api_client.go
  client-go/clientset/versioned/typed/api/v1alpha2/doc.go
  client-go/clientset/versioned/typed/api/v1alpha2/fake/doc.go
  client-go/clientset/versioned/typed/api/v1alpha2/fake/fake_api_client.go
  client-go/clientset/versioned/typed/api/v1alpha2/fake/fake_inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha2/fake/fake_inferencepool.go
  client-go/clientset/versioned/typed/api/v1alpha2/generated_expansion.go
  client-go/clientset/versioned/typed/api/v1alpha2/inferencemodel.go
  client-go/clientset/versioned/typed/api/v1alpha2/inferencepool.go
  client-go/informers/externalversions/api/interface.go
  client-go/informers/externalversions/api/v1alpha2/inferencemodel.go
  client-go/informers/externalversions/api/v1alpha2/inferencepool.go
  client-go/informers/externalversions/api/v1alpha2/interface.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/listers/api/v1alpha2/expansion_generated.go
  client-go/listers/api/v1alpha2/inferencemodel.go
  client-go/listers/api/v1alpha2/inferencepool.go
  hack/boilerplate.go.txt
Labels: cncf-cla: yes, approved, lgtm, size/M

#561 Allow partial metric updates
  pkg/epp/backend/metrics/metrics.go
  pkg/epp/backend/metrics/pod_metrics.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#550 Configure the vllm deployment with best practices for startup
  config/manifests/vllm/gpu-deployment.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#573 Configure gpu-deployment.yaml to force vLLM v1 with LoRA
  config/manifests/vllm/gpu-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#583 Cleanup logging in the request scheduling path
  pkg/epp/backend/metrics/logger.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#588 minor update to Makefile
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#585 Add provider-specific manifests for BBR helm chart
  config/charts/body-based-routing/README.md
  config/charts/body-based-routing/templates/gke.yaml
  config/charts/body-based-routing/templates/istio.yaml
  config/charts/body-based-routing/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#590 helm-improvements
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/_validations.tpl
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/epp-service.yaml
  config/charts/inferencepool/templates/inferencepool.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#578 Updating llama 2 7b to llama 3.1 8b Instruct and adding new LoRA adapters
  config/charts/inferencepool/README.md
  config/charts/inferencepool/values.yaml
  config/manifests/benchmark/benchmark.yaml
  config/manifests/gateway/patch_policy.yaml
  config/manifests/inferencemodel.yaml
  config/manifests/inferencepool.yaml
  config/manifests/vllm/cpu-deployment.yaml
  config/manifests/vllm/gpu-deployment.yaml
  hack/test-e2e.sh
  pkg/epp/datastore/datastore_test.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/response_test.go
  site-src/guides/adapter-rollout.md
  site-src/guides/index.md
  site-src/guides/metrics.md
  test/e2e/epp/README.md
  test/e2e/epp/e2e_suite_test.go
  test/integration/epp/hermetic_test.go
  test/testdata/envoy.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
  tools/dynamic-lora-sidecar/deployment.yaml
  tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
Labels: cncf-cla: yes, size/L, approved, lgtm

#592 Renaming resources to better mirror how names are expected to be used
  config/manifests/inferencemodel.yaml
  config/samples/gateway_v1alpha1_inferencemodel.yaml
  config/samples/gateway_v1alpha1_inferencepool.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#580 update algorithm parameters from env variables
  pkg/epp/scheduling/filter.go
  pkg/epp/scheduling/filter_test.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/util/env/env.go
  pkg/epp/util/env/env_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#559 update benchmarking guide with latest results with vllm v1
  site-src/performance/benchmark/example-bar-chart.png
  site-src/performance/benchmark/index.md
  site-src/performance/benchmark/sample.json
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#595 Added provider support to InferencePool helm chart
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/NOTES.txt
  config/charts/inferencepool/templates/_helpers.tpl
  config/charts/inferencepool/templates/_validations.tpl
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/gke.yaml
  config/charts/inferencepool/templates/inferencepool.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#605 make dynamic lora sidecar health check parameters configurable and force reconcile
  tools/dynamic-lora-sidecar/Dockerfile
  tools/dynamic-lora-sidecar/README.md
  tools/dynamic-lora-sidecar/screenshots/configmap-change.png
  tools/dynamic-lora-sidecar/screenshots/lora-syncer-logs.png
  tools/dynamic-lora-sidecar/screenshots/lora-syncer-sidecar.png
  tools/dynamic-lora-sidecar/sidecar/sidecar.py
  tools/dynamic-lora-sidecar/sidecar/test_sidecar.py
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#606 Fix verbosity flag in BBR helm chart
  config/charts/body-based-routing/templates/bbr.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, needs-ok-to-test

#601 Add support for configuring ports in BBR helm chart
  config/charts/body-based-routing/README.md
  config/charts/body-based-routing/templates/bbr.yaml
  config/charts/body-based-routing/templates/gke.yaml
  config/charts/body-based-routing/templates/istio.yaml
  config/charts/body-based-routing/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S, needs-ok-to-test

#611 Fix label selector on the ClusterPodMonitoring object
  config/charts/inferencepool/templates/gke.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#608 Removing obsolete part of metrics guide
  site-src/guides/metrics.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#609 Allow defining a default base model in the lora syncer configuration
  config/manifests/vllm/gpu-deployment.yaml
  site-src/guides/adapter-rollout.md
  tools/dynamic-lora-sidecar/README.md
  tools/dynamic-lora-sidecar/deployment.yaml
  tools/dynamic-lora-sidecar/sidecar/sidecar.py
  tools/dynamic-lora-sidecar/sidecar/validation.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#612 add namespace parameter to ClusterPodMonitoring secret reference
  config/charts/inferencepool/Chart.yaml
  config/charts/inferencepool/templates/gke.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#613 Various fixes to docs and example manifests names
  README.md
  config/manifests/inferencemodel.yaml
  config/manifests/vllm/gpu-deployment.yaml
  site-src/guides/adapter-rollout.md
  tools/dynamic-lora-sidecar/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#615 Docs: Quickstart Fixes
  config/manifests/gateway/httproute-with-timeout.yaml
  config/manifests/gateway/httproute.yaml
  config/manifests/inferencemodel.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#614 Adding terminationGracePeriodSeconds to match vLLMs
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/manifests/inferencepool-resources.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#604 Add running request gauge metric
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/running_requests_metrics
  site-src/guides/metrics.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#622 [Metrics] Add number of ready pods metric for inference pool
  pkg/epp/backend/metrics/logger.go
  pkg/epp/metrics/metrics.go
  site-src/guides/metrics.md
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M
