Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-04, with the labels that each got.

#623 Fixes Adapter ConfigMap Name Refs
  config/manifests/vllm/gpu-deployment.yaml
  tools/dynamic-lora-sidecar/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#616 Fixes Kgateway in Quickstart Guide
  config/manifests/gateway/gke/httproute.yaml
  config/manifests/gateway/istio/httproute.yaml
  config/manifests/gateway/kgateway/httproute.yaml
  site-src/guides/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#625 Update release script
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/S

#628 More release updates
  hack/push-chart.sh
  hack/release-quickstart.sh
Labels: cncf-cla: yes, approved, lgtm, size/S

#630 Adding larger logo
  site-src/images/logo/logo-text-xl-dark.png
Labels: cncf-cla: yes, size/XS, approved, lgtm

#633 Minor fixes to the user guide
  config/manifests/gateway/gke/healthcheck.yaml
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#631 Add istio to implementations.md
  site-src/implementations.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#636 Update e2e test config
  test/e2e/epp/e2e_test.go
  test/testdata/envoy.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#638 Fix parsing issue in BBR helm
  config/charts/body-based-routing/README.md
  config/charts/body-based-routing/templates/gke.yaml
  config/charts/body-based-routing/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#639 Patch main/d9f737 to 0.3 release
  config/charts/body-based-routing/README.md
  config/charts/body-based-routing/templates/gke.yaml
  config/charts/body-based-routing/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#618 fixed bug - sleep is expecting to get a string
  config/manifests/vllm/gpu-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#634 #632 Add favicon for doc site
  mkdocs.yml
  site-src/images/favicon-64.png
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#626 Move integration test utils to central package
  test/integration/epp/hermetic_test.go
  test/integration/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#640 BBR readme fixes
  config/charts/body-based-routing/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#627 Add integration tests to exercise streaming mode in BBR
  pkg/body-based-routing/handlers/server.go
  test/integration/bbr/hermetic_test.go
  test/integration/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#644 Adding 2 new reviewers to the reviewers alias
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#635 Add initial implementer's guide
  site-src/guides/implementers.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#629 Update BBR istio.yaml to use FULL_DUPLEX_STREAMED mode
  config/charts/body-based-routing/templates/istio.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#649 remove deprecated v1alpha2.AddToScheme and use v1alpha2.Install instead
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/server/controller_manager.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#648 removed time.sleep and using ticker instead
  pkg/epp/backend/metrics/logger.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#653 update release version in README
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#621 fix some issues in e2e tests
  test/e2e/epp/e2e_suite_test.go
  test/e2e/epp/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#654 Getting started docs version bump
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#643 expose "Normalized Time Per Output Token" (NTPOT) metric
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/normalized_time_per_output_token_seconds_metric
  site-src/guides/metrics.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#652 fix manifests and description in the user guides
  config/manifests/inferencemodel.yaml
  config/manifests/vllm/gpu-deployment.yaml
  pkg/epp/README.md
  site-src/guides/adapter-rollout.md
  site-src/guides/index.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#642 adjust the gpu deployment to increase max batch size
  config/manifests/vllm/gpu-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#663 Cleaning up config pkg
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/inferencemodel_editor_role.yaml
  config/rbac/inferencemodel_viewer_role.yaml
  config/rbac/inferencepool_editor_role.yaml
  config/rbac/inferencepool_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/gateway_v1alpha1_inferencemodel.yaml
  config/samples/gateway_v1alpha1_inferencepool.yaml
  config/samples/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL

#664 Rename pkg/body-based-routing to pkg/bbr
  cmd/bbr/health.go
  cmd/bbr/main.go
  pkg/bbr/README.md
  pkg/bbr/handlers/request.go
  pkg/bbr/handlers/request_test.go
  pkg/bbr/handlers/response.go
  pkg/bbr/handlers/server.go
  pkg/bbr/handlers/server_test.go
  pkg/bbr/metrics/metrics.go
  pkg/bbr/server/runserver.go
  test/integration/bbr/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#666 deploy: Enable logging for GKE gateway by default
  config/charts/inferencepool/templates/gke.yaml
  config/manifests/gateway/gke/gcp-backend-policy.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#662 moved IsPodReady func to podutils
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/datastore/datastore.go
  pkg/epp/util/pod/pod.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#668 removed double loop on docs in hermetic test
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#669 fix bbr dockerfile that was broken in PR #664
  Makefile
  bbr.Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/S

#665 cleaning up inferencePool helm docs
  config/charts/inferencepool/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#670 move inf model IsCritial func out of datastore
  pkg/epp/datastore/datastore.go
  pkg/epp/handlers/request.go
  pkg/epp/handlers/streamingserver.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#672 Consolidating down to FULL_DUPLEX_STREAMED supported ext-proc server
  cmd/epp/main.go
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/manifests/inferencepool-resources.yaml
  pkg/epp/handlers/request.go
  pkg/epp/handlers/response.go
  pkg/epp/handlers/response_test.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#702 minor changes in few places
  config/manifests/inferencepool-resources.yaml
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/server/controller_manager.go
  pkg/epp/server/runserver.go
  site-src/implementations/gateways.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#701 Docs: Adds Kgateway Cleanup to Quickstart
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M, do-not-merge/hold

#707 using namespaced name
  cmd/epp/main.go
  pkg/epp/server/controller_manager.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#683 EPP Architecture proposal
  docs/proposals/00x-epp-compliance-proposal/README.md
  docs/proposals/00x-epp-compliance-proposal/images/epp_arch.svg
Labels: cncf-cla: yes, size/L, approved, lgtm

#723 removed unused Fake struct
  pkg/epp/backend/metrics/fake.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#726 epp: return correct response for trailers
  pkg/epp/handlers/server.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#677 Refactor scheduler to run plugins
  pkg/epp/backend/metrics/types.go
  pkg/epp/handlers/request.go
  pkg/epp/handlers/server.go
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/scheduler_plugin_processing_latencies_metric
  pkg/epp/scheduling/config/config.go
  pkg/epp/scheduling/plugins/filter.go
  pkg/epp/scheduling/plugins/filter_test.go
  pkg/epp/scheduling/plugins/noop.go
  pkg/epp/scheduling/plugins/picker.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/interfaces.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#673 Complete the InferencePool documentation
  api/v1alpha2/inferencemodel_types.go
  mkdocs.yml
  site-src/api-types/inferencepool.md
  site-src/guides/replacing-inference-pool.md
  site-src/reference/spec.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#708 reduce log level in metrics logger not to trash the log
  cmd/epp/main.go
  pkg/epp/backend/metrics/logger.go
  pkg/epp/server/runserver.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#713 few updates in datastore
  pkg/epp/controller/inferencemodel_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/util/pod/pod.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#730 scheduler restructuring
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/scheduling/plugins/filter/filter.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/noop.go
  pkg/epp/scheduling/plugins/picker/random_picker.go
  pkg/epp/scheduling/plugins/plugins.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#696 filter irrelevant pods in pod controller
  pkg/epp/controller/pod_reconciler.go
  pkg/epp/datastore/datastore.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#731 EPP: Update GetRandomPod() to return nil if no pods exist
  pkg/epp/handlers/request.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/streamingserver_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#738 Update issue templates
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/new-release.md
Labels: cncf-cla: yes, approved, lgtm, size/S

#712 Add unit tests for pod APIs under pkg/datastore
  pkg/epp/datastore/datastore_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#739 added a target dedicated for running unit-test only
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#741 Updating proposal directories to match their PR number
  docs/proposals/0683-epp-architecture-proposal/README.md
  docs/proposals/0683-epp-architecture-proposal/images/epp_arch.svg
  docs/proposals/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#742 Fixing errors in new template & disabling the default blank template
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#750 fixed broken link to implementations
  site-src/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#737 Weighted scorers
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/default_config.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/plugins/noop.go
  pkg/epp/scheduling/plugins/picker/random_picker.go
  pkg/epp/scheduling/plugins/plugins.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#752 add max score picker
  pkg/epp/scheduling/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/plugins/picker/random_picker.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#758 Add GetEnvString helper function
  pkg/epp/util/env/env.go
  pkg/epp/util/env/env_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#751 extract pod representation from backend/metrics to backend
  pkg/epp/backend/metrics/fake.go
  pkg/epp/backend/metrics/metrics.go
  pkg/epp/backend/metrics/metrics_test.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/backend/pod.go
  pkg/epp/handlers/server.go
  pkg/epp/scheduling/plugins/filter/filter_test.go
  pkg/epp/scheduling/scheduler_test.go
  pkg/epp/scheduling/types/types.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#748 Request for adding Alibaba Cloud Container Service for Kubernetes (ACK) into implementations
  site-src/implementations/gateways.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#759 fixed error message in scheduler when no pods are available
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#720 feat: Initial setup for conformance test suite
  Makefile
  conformance/conformance.go
  conformance/conformance_test.go
  conformance/embed.go
  conformance/reports/README.md
  conformance/resources/manifests/manifests.yaml
  conformance/tests/basic/inferencepool_accepted.go
  conformance/tests/basic/inferencepool_accepted.yaml
  conformance/tests/main.go
  conformance/utils/assertions.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/traffic/traffic.go
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#744 Add inference_extension_info metric for project metadata
  Dockerfile
  cmd/epp/main.go
  pkg/epp/metrics/metrics.go
  site-src/guides/metrics.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#764 chore: make SchedulerConfig fields configurable
  pkg/epp/scheduling/config.go
  pkg/epp/scheduling/scheduler.go
  pkg/epp/scheduling/scheduler_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#765 Small refactor to capture request data for route.
  pkg/epp/handlers/request.go
  pkg/epp/handlers/server.go
  pkg/epp/handlers/server_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#762 Add queue and kv-cache scorers
  pkg/epp/scheduling/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/plugins/scorer/kvcache.go
  pkg/epp/scheduling/plugins/scorer/kvcache_test.go
  pkg/epp/scheduling/plugins/scorer/queue.go
  pkg/epp/scheduling/plugins/scorer/queue_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#767 Add scheduler e2e latency metric
  pkg/epp/metrics/metrics.go
  pkg/epp/metrics/metrics_test.go
  pkg/epp/metrics/testdata/scheduler_e2e_duration_seconds_metric
  pkg/epp/metrics/testdata/scheduler_plugin_processing_latencies_metric
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, size/L, approved, lgtm
