Repository kubernetes-sigs/gateway-api-inference-extension, pull requests merged in 2025-08, with the labels that each got.

#1232 refactor(conformance): restructure tests and resources
  conformance/conformance.go
  conformance/resources/base.yaml
  conformance/resources/resourcename.go
  conformance/tests/basic/httproute_invalid_inferencepool_ref.yaml
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/epp_unavailable_fail_open.yaml
  conformance/tests/gateway_following_epp_routing.go
  conformance/tests/gateway_following_epp_routing.yaml
  conformance/tests/httproute_invalid_inferencepool_ref.go
  conformance/tests/httproute_invalid_inferencepool_ref.yaml
  conformance/tests/httproute_multiple_gateways_different_pools.go
  conformance/tests/httproute_multiple_gateways_different_pools.yaml
  conformance/tests/inferencepool_accepted.go
  conformance/tests/inferencepool_accepted.yaml
  conformance/tests/inferencepool_httproute_port_validation.go
  conformance/tests/inferencepool_httproute_port_validation.yaml
  conformance/tests/inferencepool_invalid_epp_service.go
  conformance/tests/inferencepool_invalid_epp_service.yaml
  conformance/tests/inferencepool_multiple_rules_different_pools.go
  conformance/tests/inferencepool_multiple_rules_different_pools.yaml
  conformance/tests/inferencepool_resolvedrefs_condition.go
  conformance/tests/inferencepool_resolvedrefs_condition.yaml
  pkg/epp/scheduling/framework/plugins/test/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/test/filter/request_header_based_filter.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1261 Refactor(conformance): merge similar helper functions and make the condition check on inferencePool stricter
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/gateway_following_epp_routing.go
  conformance/tests/inferencepool_accepted.go
  conformance/tests/inferencepool_httproute_port_validation.go
  conformance/tests/inferencepool_invalid_epp_service.go
  conformance/tests/inferencepool_resolvedrefs_condition.go
  conformance/utils/kubernetes/helpers.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1121 Update lora affinity to be a scorer.
  cmd/epp/runner/runner.go
  pkg/epp/scheduling/framework/plugins/scorer/lora_affinity.go
  pkg/epp/scheduling/framework/plugins/scorer/lora_affinity_test.go
  site-src/guides/epp-configuration/config-text.md
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1287 Fixes for `make fmt-imports`
  conformance/conformance.go
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/httproute_invalid_inferencepool_ref.go
  pkg/epp/flowcontrol/controller/internal/processor.go
  pkg/epp/flowcontrol/controller/internal/processor_test.go
  pkg/epp/scheduling/framework/plugins/scorer/lora_affinity_test.go
  pkg/epp/scheduling/scheduler.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1282 adding fairness-id header to be used in flow control
  cmd/epp/runner/runner.go
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/templates/rbac.yaml
  pkg/epp/handlers/request.go
  pkg/epp/handlers/request_test.go
  pkg/epp/handlers/server.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/server/runserver.go
  pkg/epp/server/server_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1297 Rename lora affinity plugin to lora-affinity-scorer to be consistent with others
  pkg/epp/scheduling/framework/plugins/scorer/lora_affinity.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1300 revert #1010 to resume new main EPP image build
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1277 feat: changed to support both v1 and v1a2 ip in EPP
  Dockerfile
  cmd/epp/runner/runner.go
  pkg/common/convert.go
  pkg/common/kubemeta.go
  pkg/epp/controller/inferenceobjective_reconciler.go
  pkg/epp/controller/inferenceobjective_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/server/controller_manager.go
  pkg/epp/server/runserver.go
  pkg/epp/util/testing/wrappers.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1311 Updating tabs to spaces
  docs/proposals/1199-inferencemodel-api-evolution/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1237 Pluggable metrics collection
  go.mod
  go.sum
  pkg/epp/datalayer/attributemap.go
  pkg/epp/datalayer/collector.go
  pkg/epp/datalayer/collector_test.go
  pkg/epp/datalayer/datasource.go
  pkg/epp/datalayer/datasource_test.go
  pkg/epp/datalayer/endpoint.go
  pkg/epp/datalayer/metrics/client.go
  pkg/epp/datalayer/metrics/datasource.go
  pkg/epp/datalayer/metrics/extractor.go
  pkg/epp/datalayer/metrics/loraspec.go
  pkg/epp/datalayer/metrics/mapping.go
  pkg/epp/datalayer/metrics/spec.go
  pkg/epp/datalayer/metrics/spec_test.go
  pkg/epp/datalayer/metrics/types.go
  pkg/epp/datalayer/mocks/ticker.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1314 Removing concurrency issues from Random Picker
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
  pkg/epp/scheduling/framework/plugins/picker/random_picker.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1318 Docs: Bumps kgateway Version in Quickstart
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1317 Conformance: Adds Report for kgateway
  conformance/reports/v0.5.1/gateway/kgateway/README.md
  conformance/reports/v0.5.1/gateway/kgateway/inference-v2.0.4-report.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#1294 Refactor the configuration defaults handling code
  apix/config/v1alpha1/defaults.go
  apix/config/v1alpha1/endpointpickerconfig_types.go
  apix/config/v1alpha1/zz_generated.defaults.go
  cmd/epp/runner/runner.go
  config/charts/inferencepool/templates/epp-config.yaml
  config/charts/inferencepool/values.yaml
  config/manifests/inferencepool-resources.yaml
  conformance/resources/base.yaml
  pkg/epp/config/config.go
  pkg/epp/config/loader/configloader.go
  pkg/epp/config/loader/configloader_test.go
  pkg/epp/config/loader/defaults.go
  site-src/guides/epp-configuration/config-text.md
  site-src/guides/inferencepool-rollout.md
  test/testdata/inferencepool-e2e.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1322 refactor: 👷 clean unused randomGenerator parameter.
  pkg/epp/scheduling/framework/plugins/picker/max_score_picker.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1296 remove protocol specifics from cmd-line flags
  cmd/epp/runner/runner.go
  pkg/epp/handlers/request.go
  pkg/epp/handlers/request_test.go
  pkg/epp/handlers/server.go
  pkg/epp/metadata/consts.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/server/runserver.go
  pkg/epp/server/server_test.go
  test/e2e/epp/e2e_test.go
  test/integration/epp/hermetic_test.go
  test/integration/util.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1334 Correcting title name
  docs/proposals/1199-inferencemodel-api-evolution/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1345 docs: Enable GIE in Istio installation command
  site-src/guides/index.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1346 InferenceObjective: Updates `PoolRef` Group Version
  apix/v1alpha2/inferenceobjective_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1348 Modifying Criticality; from string, to int
  apix/v1alpha2/inferenceobjective_types.go
  apix/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjectivespec.go
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  config/manifests/inferenceobjective.yaml
  config/manifests/regression-testing/inferenceobjective.yaml
  conformance/tests/epp_unavailable_fail_open.yaml
  conformance/tests/gateway_following_epp_routing.yaml
  pkg/epp/controller/inferenceobjective_reconciler_test.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/util/testing/wrappers.go
  site-src/guides/adapter-rollout.md
  site-src/guides/inferencepool-rollout.md
  site-src/guides/serve-multiple-lora-adapters.md
  test/e2e/epp/e2e_test.go
  test/testdata/inferencepool-with-model-hermetic.yaml
  test/utils/wrappers.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1310 cleanup: fix typo and delete useless parameter
  cmd/epp/runner/runner.go
  pkg/epp/backend/metrics/logger.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/controller/inferenceobjective_reconciler_test.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/metrics/collectors/inference_pool.go
  pkg/epp/metrics/collectors/inference_pool_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/saturationdetector/saturationdetector.go
  test/integration/epp/hermetic_test.go
  test/utils/server.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#1340 refactor(flowcontrol): Adopt Composite FlowKey as Primary Identifier
  pkg/epp/flowcontrol/contracts/mocks/mocks.go
  pkg/epp/flowcontrol/contracts/registry.go
  pkg/epp/flowcontrol/controller/internal/filter.go
  pkg/epp/flowcontrol/controller/internal/filter_test.go
  pkg/epp/flowcontrol/controller/internal/item_test.go
  pkg/epp/flowcontrol/controller/internal/processor.go
  pkg/epp/flowcontrol/controller/internal/processor_test.go
  pkg/epp/flowcontrol/framework/mocks/mocks.go
  pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/besthead/besthead_test.go
  pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/functional_test.go
  pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/roundrobin/roundrobin.go
  pkg/epp/flowcontrol/framework/plugins/policies/interflow/dispatch/roundrobin/roundrobin_test.go
  pkg/epp/flowcontrol/framework/plugins/policies/intraflow/dispatch/fcfs/fcfs_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/benchmark_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/functional_test.go
  pkg/epp/flowcontrol/framework/plugins/queue/maxminheap/maxminheap_test.go
  pkg/epp/flowcontrol/framework/policies.go
  pkg/epp/flowcontrol/registry/doc.go
  pkg/epp/flowcontrol/registry/managedqueue.go
  pkg/epp/flowcontrol/registry/managedqueue_test.go
  pkg/epp/flowcontrol/registry/shard.go
  pkg/epp/flowcontrol/registry/shard_test.go
  pkg/epp/flowcontrol/types/flow.go
  pkg/epp/flowcontrol/types/mocks/mocks.go
  pkg/epp/flowcontrol/types/request.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#1353 Conformance: Adds InferenceObjective Request Header
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/gateway_following_epp_routing.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#1349 test: enhance plugin state test coverage and readability
  pkg/epp/plugins/plugin_state.go
  pkg/epp/plugins/plugin_state_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1355 refactor(conformance): Relocate constants to minimize package dependencies
  conformance/resources/resourcename.go
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/gateway_following_epp_routing.go
  pkg/epp/scheduling/framework/plugins/test/consts.go
  pkg/epp/scheduling/framework/plugins/test/filter/filter_test.go
  pkg/epp/scheduling/framework/plugins/test/filter/request_header_based_filter.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#1359 [BBR] perf: optimize model name extraction with selective JSON unmarshaling using struct tags
  pkg/bbr/handlers/request.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1363 Rename criticality to priority
  apix/v1alpha2/inferenceobjective_types.go
  apix/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/apix/v1alpha2/inferenceobjectivespec.go
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  config/manifests/inferenceobjective.yaml
  config/manifests/regression-testing/inferenceobjective.yaml
  pkg/epp/controller/inferenceobjective_reconciler_test.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/util/testing/wrappers.go
  test/e2e/epp/e2e_test.go
  test/testdata/inferencepool-with-model-hermetic.yaml
  test/utils/wrappers.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1330 Upgrade the inferencePool selector to a struct from a map.
  api/v1/inferencepool_types.go
  api/v1/shared_types.go
  api/v1/zz_generated.deepcopy.go
  apix/v1alpha2/inferencepool_conversion.go
  apix/v1alpha2/inferencepool_conversion_test.go
  apix/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1/inferencepoolspec.go
  client-go/applyconfiguration/api/v1/labelselector.go
  client-go/applyconfiguration/utils.go
  config/charts/inferencepool/templates/inferencepool.yaml
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  config/manifests/inferencepool-resources.yaml
  conformance/resources/base.yaml
  pkg/common/convert.go
  pkg/epp/controller/inferencepool_reconciler.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/util/testing/wrappers.go
  test/testdata/inferencepool-e2e.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#1351 Pluggable data layer: transition `backend/metrics` to use type aliases from `datalayer` package
  pkg/epp/backend/metrics/fake.go
  pkg/epp/backend/metrics/logger.go
  pkg/epp/backend/metrics/metrics_state.go
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/backend/metrics/types.go
  pkg/epp/backend/pod.go
  pkg/epp/datalayer/endpoint.go
  pkg/epp/datalayer/factory.go
  pkg/epp/datastore/datastore.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1377 docs: match Inference Extension CRDs
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1354 feat: TargetPortNumber int32 to become TargetPorts []Port
  api/v1/inferencepool_types.go
  api/v1/zz_generated.deepcopy.go
  apix/v1alpha2/inferencepool_conversion.go
  apix/v1alpha2/inferencepool_conversion_test.go
  apix/v1alpha2/inferencepool_types.go
  apix/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/api/v1/inferencepoolspec.go
  client-go/applyconfiguration/api/v1/port.go
  client-go/applyconfiguration/utils.go
  cmd/epp/runner/runner.go
  config/charts/inferencepool/templates/inferencepool.yaml
  config/charts/inferencepool/values.yaml
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
  config/manifests/inferencepool-resources.yaml
  conformance/resources/base.yaml
  pkg/epp/backend/metrics/pod_metrics.go
  pkg/epp/backend/metrics/pod_metrics_test.go
  pkg/epp/controller/inferencepool_reconciler_test.go
  pkg/epp/controller/pod_reconciler_test.go
  pkg/epp/datastore/datastore_test.go
  pkg/epp/handlers/request.go
  pkg/epp/metrics/collectors/inference_pool_test.go
  pkg/epp/requestcontrol/director.go
  pkg/epp/requestcontrol/director_test.go
  pkg/epp/util/testing/wrappers.go
  site-src/api-types/inferencepool.md
  site-src/guides/implementers.md
  site-src/guides/inferencepool-rollout.md
  test/testdata/inferencepool-e2e.yaml
  test/testdata/inferencepool-with-model-hermetic.yaml
  test/utils/server.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1369 Update doc on sglang models support.
  docs/proposals/003-model-server-protocol/README.md
  site-src/implementations/model-servers.md
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1375 feat: added shortname as alias
  api/v1/inferencepool_types.go
  apix/v1alpha2/inferencepool_types.go
  config/crd/bases/inference.networking.k8s.io_inferencepools.yaml
  config/crd/bases/inference.networking.x-k8s.io_inferencepools.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#1385 Tooling: Adds PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#1019 docs: add prometheus + grafana deployment guide
  config/observability/prometheus/rbac.yaml
  config/observability/prometheus/values.yaml
  site-src/guides/metrics-and-observability.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#1067 docs: how to debug integration tests
  site-src/contributing/devguide.md
  site-src/images/edit-environment-variables.png
  site-src/images/modify-run-configuration.png
  site-src/images/running-example.png
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1388 Fixes Quickstart Script
  hack/release-quickstart.sh
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S

#1378 gitignore macOS generated files.
  .gitignore
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1328 feat: added env var for pool group
  cmd/epp/runner/runner.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1402 Fix: Handle empty string healthcheck as readiness healthcheck
  cmd/epp/runner/health.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm, kind/failing-test, ok-to-test

#1392 depreacte post cycle from scheduling framework
  pkg/epp/config/loader/configloader_test.go
  pkg/epp/config/loader/defaults.go
  pkg/epp/plugins/plugin_state_test.go
  pkg/epp/scheduling/framework/plugins.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
  pkg/epp/scheduling/framework/scheduler_profile.go
  pkg/epp/scheduling/framework/scheduler_profile_test.go
  pkg/epp/scheduling/scheduler_test.go
  test/integration/epp/hermetic_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1419 Conformance: Fixes Secondary InferencePool Selector
  conformance/resources/base.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm, kind/failing-test

#1413 Fix Makefile syntax and version consistency
  Makefile
  bbr.Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1391 Enable pluggable datalayer as experimental feature
  cmd/epp/runner/runner.go
  pkg/epp/datalayer/collector.go
  pkg/epp/datalayer/datasource.go
  pkg/epp/datalayer/factory.go
  pkg/epp/datalayer/metrics/client.go
  pkg/epp/datalayer/metrics/datasource.go
  pkg/epp/datalayer/metrics/logger.go
  pkg/epp/datastore/datastore.go
  pkg/epp/server/runserver.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#1395 trace logging for scores per pod
  pkg/epp/scheduling/framework/scheduler_profile.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#1397 remove env vars for cmd-lind args
  cmd/epp/runner/runner.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1302 Ensure EPP flags are configurable via Helm chart
  config/charts/inferencepool/README.md
  config/charts/inferencepool/templates/epp-deployment.yaml
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1429 Cleanup helm flags which have default values from values yaml
  config/charts/inferencepool/README.md
  config/charts/inferencepool/values.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1439 Fix epp startup error due to missing plugin config file flag
  config/charts/inferencepool/templates/epp-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1370 Update inference gateway public docs to use helm charts
  site-src/guides/index.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1437 Fix typo.
  apix/v1alpha2/inferenceobjective_types.go
  config/crd/bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
  site-src/reference/x-spec.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1445 remove wg serving leads from owners file
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1341 fix: first hash of prefix cache with same model name
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1448 adding mutex and contention profile gathering
  cmd/epp/runner/runner.go
Labels: cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1447 remove empty condition list when doing v1 and v1alpha2 conversion.
  apix/v1alpha2/inferencepool_conversion.go
  apix/v1alpha2/inferencepool_conversion_test.go
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#1451 Updates InferencePool API Conversion Code
  apix/v1alpha2/inferencepool_conversion.go
  apix/v1alpha2/inferencepool_conversion_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#1430 Add initial troubleshooting guide
  mkdocs.yml
  site-src/guides/troubleshooting.md
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test, kind/documentation

#1453 fix: ping to vllm v0.8.5
  config/manifests/regression-testing/vllm/multi-lora-deployment.yaml
  config/manifests/vllm/gpu-deployment.yaml
  site-src/guides/inferencepool-rollout.md
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#1472 Updating proposal statuses
  docs/proposals/002-api-proposal/README.md
  docs/proposals/003-model-server-protocol/README.md
  docs/proposals/004-endpoint-picker-protocol/README.md
  docs/proposals/006-scheduler/README.md
  docs/proposals/0602-prefix-cache-aware-routing-proposal/README.md
  docs/proposals/0683-epp-architecture-proposal/README.md
  docs/proposals/0845-scheduler-architecture-proposal/README.md
  docs/proposals/1023-data-layer-architecture/README.md
  docs/proposals/1199-inferencemodel-api-evolution/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#1477 fix(conformance): remove the inferenceObjective dependency compeletely.
  conformance/resources/resourcename.go
  conformance/tests/epp_unavailable_fail_open.go
  conformance/tests/epp_unavailable_fail_open.yaml
  conformance/tests/gateway_following_epp_routing.go
  conformance/tests/gateway_following_epp_routing.yaml
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M

#1478 Add Alibaba Cloud ack-gie conformance report for v0.5.1
  conformance/reports/v0.5.1/gateway/ack-gateway/README.md
  conformance/reports/v0.5.1/gateway/ack-gateway/v1.4.0-apsara.3-gateway-report.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1485 Fix troubleshooting guide
  site-src/guides/troubleshooting.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test, kind/documentation

#1491 use context in indexer go routine instead of context.TODO
  pkg/epp/scheduling/framework/plugins/multi/prefix/indexer.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/indexer_test.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
Labels: cncf-cla: yes, approved, lgtm, size/S, kind/cleanup

#1316 Adding conformance report for Kubvernor
  conformance/reports/v0.5.1/gateway/kubvernor/README.md
  conformance/reports/v0.5.1/gateway/kubvernor/kubvernor-inference-conformance-output-0.1.1.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1499 fix(conformance) add endpointConfig port in conformance test for v1 as it's required for service kind now.
  conformance/resources/base.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1214 feat(conformance): Use CRD annotation to populate the ConformanceReport GatewayAPIInferenceExtensionVersion
  conformance/conformance.go
Labels: cncf-cla: yes, approved, lgtm, size/M, ok-to-test

#1490 if request id was not supplied in header, generate uuid
  pkg/epp/handlers/server.go
  pkg/epp/plugins/plugin_state.go
  pkg/epp/server/server_test.go
  test/integration/epp/hermetic_test.go
  test/integration/util.go
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#1509 prefix state temp fix - write state to both plugin state and cycle state
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go
  pkg/epp/scheduling/framework/plugins/multi/prefix/plugin_test.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/M

#1508 allow setting custom plugins file through helm
  config/charts/inferencepool/templates/epp-deployment.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm
